### ISSUE TITLE
ptah, and weapon plugin dont show up at meta list and dont work.

### ISSUE THREAD

**Issue by killzone559pl** [kgns/weapons#101]
Hello, both plugins doesnt work at all, sourcemod and metamod are working, but when im entering on server and when i type !ws nothing show up, i dont have any errors too.

**Comment by killzone559pl** [comment]
I repaired problem, but now !ws dont work at all, i can choose skins to weapons but they do not apply. !knife works.

**Comment by kgns** [comment]
Follow the steps on https://forums.alliedmods.net/showthread.php?t=298770 carefully and make sure you don't skip any steps and install the correct versions of requirements. Everything is working as it's supposed to. If it's not working for you, then you probably did not follow the instructions
