### ISSUE TITLE
When typing quit to console server crashes

### ISSUE THREAD

**Issue by Prefix** [kgns/weapons#102]
SteamGameServer_Shutdown
L 08/11/2019 - 12:06:01: server_message: "quit"
L 08/11/2019 - 12:06:01: Log file closed
L 08/11/2019 - 12:06:01: server_message: "restart"
SV_ShutdownGameDLL
Segmentation fault
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Sun Aug 11 12:06:01 EEST 2019: Server restart in 10 seconds

sm plugins list
[SM] Listing 1 plugin:
  1 "Weapons & Knives" (1.4.0) by kgns | oyunhost.net

(Yes only one plugin is fine to reproduce)

sm version
 SourceMod Version Information:
    SourceMod Version: 1.10.0.6434
    SourcePawn Engine: 1.10.0.6434, jit-x86 (build 1.10.0.6434)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Aug  1 2019 05:49:09
    Built from: https://github.com/alliedmodders/sourcemod/commit/b8fd7db
    Build ID: 6434:b8fd7db
    http://www.sourcemod.net/
meta version
 Metamod:Source Version Information
    Metamod:Source version 1.11.0-dev+1127
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Mar 28 2019 17:00:48
    Built from: https://github.com/alliedmodders/metamod-source/commit/de33074
    Build ID: 1127:de33074
    http://www.metamodsource.net/
sm exts list
[SM] Displaying 10 extensions:
[01] Automatic Updater (1.10.0.6434): Updates SourceMod gamedata files
[02] Webternet (1.10.0.6434): Extension for interacting with URLs
[03] Accelerator (2.3.3): SRCDS Crash Handler
[04] BanId Fix (1.0): Correcting 'Ghost players' error
[05] SDK Tools (1.10.0.6434): Source SDK Tools
[06] BinTools (1.10.0.6434): Low-level C/C++ Calling API
[07] CS Tools (1.10.0.6434): CS extended functionality
[08] PTaH (1.1.0): Additional CS:GO Hooks and Natives
[09] SDK Hooks (1.10.0.6434): Source SDK Hooks
[10] SQLite (1.10.0.6434): SQLite Driver

**Comment by kgns** [comment]
check https://github.com/komashchenko/PTaH/issues/21, maybe it will help you. this problem is unrelated to the plugin. open an issue on PTaH repo if this does not solve your problem
