### ISSUE TITLE
errors log

### ISSUE THREAD

**Issue by kleuser75** [kgns/weapons#111]
L 10/19/2019 - 12:15:50: SourceMod error session started
L 10/19/2019 - 12:15:50: Info (map "deathrun_iceworld_2_hp") (file "/home/kleuser/servers/test2/csgo/addons/sourcemod/logs/errors_20191019.log")
L 10/19/2019 - 12:15:50: [weapons.smx] SQLite Seed column creation failed! near "AFTER": syntax error
L 10/19/2019 - 12:16:09: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 12:16:09: [SM] Blaming: weapons.smx
L 10/19/2019 - 12:16:09: [SM] Call stack trace:
L 10/19/2019 - 12:16:09: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 12:16:09: [SM]   [1] Line 63, weapons/database.sp::T_GetPlayerDataCallback

**Comment by kgns** [comment]
try v1.4.2 and report back please

**Comment by kleuser75** [comment]
fixed
