### ISSUE TITLE
BUG SEED

### ISSUE THREAD

**Issue by Joez252** [kgns/weapons#112]
Automatic seed all the time to 0 how can I turn it off I always have a nametag of 0 and it really annoys me

**Comment by Joez252** [comment]
When i leave game and reconnect i will have random knife ?

**Comment by Joez252** [comment]
And random condition

**Comment by abdulsami34** [comment]
same here.

**Comment by abdulsami34** [comment]
Same here, Happens when changing skin. When i set bowie knife to any doppler. The name tag set to 683 or something.

**Comment by kgns** [comment]
try v1.4.2 and report back please
