### ISSUE TITLE
error_log

### ISSUE THREAD

**Issue by SanjaySRocks** [kgns/weapons#113]
L 10/19/2019 - 07:39:21: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 07:39:21: [SM] Blaming: weapons.smx
L 10/19/2019 - 07:39:21: [SM] Call stack trace:
L 10/19/2019 - 07:39:21: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 07:39:21: [SM]   [1] Line 63, tmp/addons/sourcemod/scripting/weapons/database.sp::T_GetPlayerDataCallback
L 10/19/2019 - 07:39:32: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 07:39:32: [SM] Blaming: weapons.smx
L 10/19/2019 - 07:39:32: [SM] Call stack trace:
L 10/19/2019 - 07:39:32: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 07:39:32: [SM]   [1] Line 63, tmp/addons/sourcemod/scripting/weapons/database.sp::T_GetPlayerDataCallback
L 10/19/2019 - 07:40:25: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 07:40:25: [SM] Blaming: weapons.smx
L 10/19/2019 - 07:40:25: [SM] Call stack trace:
L 10/19/2019 - 07:40:25: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 07:40:25: [SM]   [1] Line 63, tmp/addons/sourcemod/scripting/weapons/database.sp::T_GetPlayerDataCallback
L 10/19/2019 - 07:40:42: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 07:40:42: [SM] Blaming: weapons.smx
L 10/19/2019 - 07:40:42: [SM] Call stack trace:
L 10/19/2019 - 07:40:42: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 07:40:42: [SM]   [1] Line 63, tmp/addons/sourcemod/scripting/weapons/database.sp::T_GetPlayerDataCallback
L 10/19/2019 - 07:40:51: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 07:40:51: [SM] Blaming: weapons.smx
L 10/19/2019 - 07:40:51: [SM] Call stack trace:
L 10/19/2019 - 07:40:51: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 07:40:51: [SM]   [1] Line 63, tmp/addons/sourcemod/scripting/weapons/database.sp::T_GetPlayerDataCallback
L 10/19/2019 - 07:41:16: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 07:41:16: [SM] Blaming: weapons.smx
L 10/19/2019 - 07:41:16: [SM] Call stack trace:
L 10/19/2019 - 07:41:16: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 07:41:16: [SM]   [1] Line 63, tmp/addons/sourcemod/scripting/weapons/database.sp::T_GetPlayerDataCallback
L 10/19/2019 - 07:41:28: [weapons.smx] Update Player failed! query: "UPDATE weapons SET p250_seed = -1 WHERE steamid = 'STEAM_1:0:245574427'" error: "no such column: p250_seed"

**Comment by kgns** [comment]
try v1.4.2 and report back please

**Comment by SanjaySRocks** [comment]
Fixed for me no errors now.
bdw kgns can you explain what is seed option in weapon skins?

**Comment by kgns** [comment]
you can search google for csgo weapon skin seeds and learn about them, its not something i made up :)
