### ISSUE TITLE
Can't change nametag, stattrack, weapon condition or seed

### ISSUE THREAD

**Issue by flashing1998** [kgns/weapons#114]
i am not able to change nametag, stattrack, weapon condition or seed for some random weapons
and for some weapons its available
iam using mysql for db
this problem was also occurring on your previous release
![20191019131459_1](https://user-images.githubusercontent.com/52833233/67140064-653aef00-f274-11e9-89d4-0d06933b599d.jpg)

**Comment by bs7gv** [comment]
Sorry i can't help with your problem, but i have a question about the [LR] Plugin, how did you make so it says when a player ranked up in chat?

**Comment by flashing1998** [comment]
its default i did'nt change anything

**Comment by bs7gv** [comment]
Its wierd it doesn't show up at my server

**Comment by flashing1998** [comment]
i am using this one https://forums.alliedmods.net/showthread.php?t=318782

**Comment by kgns** [comment]
you have to choose a skin for your weapon first to be able to change other features
