### ISSUE TITLE
error 1.4.1

### ISSUE THREAD

**Issue by d0kt0r** [kgns/weapons#116]
L 10/19/2019 - 15:26:47: [SM] Exception reported: Error fetching data from field 248
L 10/19/2019 - 15:26:47: [SM] Blaming: weapons.smx
L 10/19/2019 - 15:26:47: [SM] Call stack trace:
L 10/19/2019 - 15:26:47: [SM]   [0] DBResultSet.FetchInt
L 10/19/2019 - 15:26:47: [SM]   [1] Line 63, tmp/addons/sourcemod/scripting/weapons/database.sp::T_GetPlayerDataCallback

**Comment by kgns** [comment]
try v1.4.2 and report back please
