### ISSUE TITLE
Error Knife

### ISSUE THREAD

**Issue by ShorMario** [kgns/weapons#118]
> Attempted to create unknown entity type weapon_knife_css!
> NULL Ent in GiveNamedItem!
> 

I upgraded to 1.4.2 and the knives and stattrack don't work

**Comment by kgns** [comment]
this error does not make any sense, are you still getting this?

**Comment by ShorMario** [comment]
yes

**Comment by AkalaGit** [comment]
(v1.4.2)
Most skins have name tags on them automatically that read "0". I had to remove the tags to get the default names back which is really annoying. The Code Red deagle skin starts at like -50,000% ware (to fix this I had to decrease the ware to set it back to 0% and then spam increase to get the skin too 100%). After setting skins and coming back on the next day I had to pick my knife and configure my !ws settings again.

**Comment by kgns** [comment]
@ShorMario are you sure you updated CSGO dedicated server to the latest? this error youre getting means the server does not know anything about the new knife, which it should if its up to date

**Comment by mmendesico** [comment]
I have the same error @kgns, unfortunately all skins appear in the list except the knives

**Comment by kgns** [comment]
any updates on this problem? this is certainly not due to the plugin itself

**Comment by mmendesico** [comment]
@kgns My only problem currently is only in the compilation of "weapons.sp", where it gives the following error "fatal error 183: cannot read from file:" PTaH ".

**Comment by kgns** [comment]
i guess people found out what they did wrong and solved this. closing it.
