### ISSUE TITLE
add latest csgo 20th skin ?

### ISSUE THREAD

**Issue by GTAmama16** [kgns/weapons#121]
hey man just wondering can u update the plugin to work with the latest update :D

**Comment by LynxMSI** [comment]
He has. You need Sourcemod 1.10 and Ptah v16.

**Comment by GTAmama16** [comment]
My bad, posted on the wrong GitHub page haha
I was asking the Shane1390’s version to be updated

**Comment by LynxMSI** [comment]
> 
> 
> My bad, posted on the wrong GitHub page haha
> I was asking the Shane1390’s version to be updated

Why? This has the same seed stuff, he merged them

**Comment by GTAmama16** [comment]
> > My bad, posted on the wrong GitHub page haha
> > I was asking the Shane1390’s version to be updated
> 
> Why? This has the same seed stuff, he merged them

soz for my bad english, but i think for the shane's version, when i use deagle i can apply skin from others weapon, like doppler or other skins
