### ISSUE TITLE
DB issue

### ISSUE THREAD

**Issue by AkalaGit** [kgns/weapons#122]
(v1.4.2)
Most skins have name tags on them automatically that read "0". I had to remove the tags to get the default names back which is really annoying. The Code Red deagle skin starts at like -50,000% ware (to fix this I had to decrease the ware to set it back to 0% and then spam increase to get the skin too 100%). After setting skins and coming back on the next day I had to pick my knife and configure my !ws settings again.

**Comment by kgns** [comment]
you probably used v1.4.1 on an SQLite database and then upgrade to 1.4.2. unfortunately this might have broken your ws knife data in the database table. check if you have any problems after resetting your database (deleting the .sq3 file or changing cfg to create another sq3 database file)

**Comment by AkalaGit** [comment]
> you probably used v1.4.1 on an SQLite database and then upgrade to 1.4.2. unfortunately this might have broken your ws knife data in the database table. check if you have any problems after resetting your database (deleting the .sq3 file or changing cfg to create another sq3 database file)

I figured it was a db issue but I don't know where the weapons db is stored. Would I just delete it and start the server to generate a new one?

**Comment by kgns** [comment]
csgo/addons/sourcemod/data/sqlite

sq3 files (databases) should be located in this folder

**Comment by AkalaGit** [comment]
That worked, thanks.
