### ISSUE TITLE
[BUG] Didn't work skin and knife changer(s)

### ISSUE THREAD

**Issue by BlackYuzia** [kgns/weapons#123]
## Info

>SourceMod: **1.10.0.6453**
>Game: **CS:GO**
>OS: **Windows**
>Ptah:  **1.1.1 build16 (windows)**
>Plugin: **1.4.2**

## Core.cfg

> "FollowCSGOServerGuidelines"	"no"
> "BlockBadPlugins"	"no"

## Error logs:

>  Empty

## Description

I try use latest version of plugin (**weapons.smx**)
I setup (install) latest version of **SM 1.10**
I setup (install) latest version of **ptah** (with support only SM 1.10)
I setup (install) latest plugin version
I change **FollowCSGOServerGuidelines** and **BlockBadPlugins** to "no" in **Core.cfg**
Then. I start server. 
I try use **!ws** and **!knife**, but when I pickup some skin or knife, knife (or skin) didn't change.
I get only "reload" of weapon (knife etc) but skin stay the same.
I did't get any error logs
I did't get any errors in other logs

Plugin was successfully loaded

>L 10/21/2019 - 18:24:04: [weapons.smx] SQLite DB connection successful
>L 10/21/2019 - 18:24:04: [weapons.smx] Inactive players' data has been deleted

## Question

@kgns  **So, this is my fail or not?**

## Screenshots

>**There, I try change knife (but no effect)**
![image](https://user-images.githubusercontent.com/25010528/67220549-aaa51b00-f432-11e9-99fa-5b5778a1db12.png)
![image](https://user-images.githubusercontent.com/25010528/67220553-ac6ede80-f432-11e9-9622-47913686e229.png)

> **There I try change skin for weapon glock (but no effect)**
![image](https://user-images.githubusercontent.com/25010528/67220656-d6280580-f432-11e9-9119-3d07d101ce5f.png)

> **There I try change skin for knife**. But, when I press on "knife" button, I was moved to weapon glock
![image](https://user-images.githubusercontent.com/25010528/67220744-040d4a00-f433-11e9-99db-c67735ac08d4.png)
![image](https://user-images.githubusercontent.com/25010528/67220753-053e7700-f433-11e9-9d10-0b2eb47bc977.png)

**Comment by kgns** [comment]
can you use PTaH 1.1.0 and try again?

**Comment by BlackYuzia** [comment]
ptah 1.1.0 => the same problem @kgns 

But, when I try ~~restart~~ reload (**sm plugins reload weapons.smx**)

I get this error:
>L 10/21/2019 - 21:57:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 10/21/2019 - 21:57:33: [SM] Blaming: weapons.smx
L 10/21/2019 - 21:57:33: [SM] Call stack trace:
L 10/21/2019 - 21:57:33: [SM]   [0] Database.Query
L 10/21/2019 - 21:57:33: [SM]   [1] Line 125, tmp/addons/sourcemod/scripting/weapons/database.sp::UpdatePlayerData
L 10/21/2019 - 21:57:33: [SM]   [2] Line 37, tmp/addons/sourcemod/scripting/weapons/menus.sp::WeaponsMenuHandler

With **ptah 1.1.1** and **ptah 1.1.0**

**Comment by BlackYuzia** [comment]
after reload plugin (weapons.smx) knife changer (and weapons skins) works:
![image](https://user-images.githubusercontent.com/25010528/67234825-80f9ed00-f44e-11e9-924d-2c62267af0cd.png)

I

**Comment by BlackYuzia** [comment]
@kgns I tested the same version (**weapons.smx 1.4.2** && **ptah 1.1.0**) on **Linux** (**Ubuntu 16.04**)

All successfully work.
But, on **Windows** (**Win 7**) I get problems (like don't work plugin if I did't restart him in console (sm plugins reload weapons.smx)
Maybe this is bug only on Windows or problems with access to files on **Win 7**(Like to sqlite db or etc?)

**Comment by Bluscream** [comment]
```
[SM] Plugin Weapons & Knives reloaded successfully.
Execing config: sourcemod\weapons.cfg
Unknown command: sm_weapons_enable_allskins
Unknown command: sm_weapons_enable_seed
L 11/06/2019 - 07:16:50: [weapons.smx] SQLite DB connection successful
L 11/06/2019 - 07:16:50: [weapons.smx] Inactive players' data has been deleted
```

**Comment by Bluscream** [comment]
Yes i can confirm it does not work on windows. Not even with reload. @kgns can't you fix this please?

Do you need anything else for fix? any log/etc?

**Comment by calvinbui** [comment]
Same problem where I have to reload the plugin with `sm plugins reload weapons.smx` on every server restart.

Running on Ubuntu and ptah 1.1.0.

**Comment by BlackYuzia** [comment]
> Running on Ubuntu and ptah 1.1.0.

Wow, this is strange :thinking:

**Comment by calvinbui** [comment]
> > Running on Ubuntu and ptah 1.1.0.
> 
> Wow, this is strange 🤔

I've switched to Ubuntu Server 18.04 (from Ubuntu Desktop) with PTah 1.1.1 and it works now

**Comment by BlackYuzia** [comment]
> > > Running on Ubuntu and ptah 1.1.0.
> > 
> > 
> > Wow, this is strange thinking
> 
> I've switched to Ubuntu Server 18.04 (from Ubuntu Desktop) with PTah 1.1.1 and it works now

@calvinbui u use **SM 1.10**?

**Comment by calvinbui** [comment]
> @calvinbui u use **SM 1.10**?

Previously I used csgosl, not sure which version of SM it came with.

Now I'm using Linux GSM which  came with SM 1.09 which I had to manually update to SM 1.10 to get PTah working

**Comment by BlackYuzia** [comment]
@calvinbui 
**SM 1.10** work with **ptah 1.1.1 || 1.1.0**
**SM 1.9** work with **ptah 1.1.0**

**weapons.smx**, 100% work with **ptah 1.1.0** and **SM 1.9** (Tested on **ubuntu 16.04**)

If u want get SM version, use command:
> sm version

**Comment by calvinbui** [comment]
Yes, but my new combination worked without having to reload

SM 1.10
PTah 1.1.1
Ubuntu 18.04

**Comment by kgns** [comment]
sourcemod plugins are OS agnostic. if something doesnt work on Windows but works on Linux, you should ask for help in PTaH repo (https://github.com/komashchenko/PTaH)

**Comment by slambingo** [comment]
For me after restarting the server, a map change fixes the skins.
