### ISSUE TITLE
can you add these knifes ?

### ISSUE THREAD

**Issue by AG4lyf** [kgns/weapons#124]
so there is a cool , actually so cool knife 
in the last year halloween update , they added knife_ghost which no one remember 
and i wish it comes back to each server so can you add this ? also there is golden knife 
if you want to 

i myself tried but as i don't have have much experience so failed misreably 

https://www.youtube.com/watch?v=B1HMoF7zD-c

**Comment by kgns** [comment]
i always intended this plugin to mimic what you can do with a real inventory. sadly that knife was a holiday special and cannot be used in matchmaking, thus i do not have any plans to include it in the plugin
