### ISSUE TITLE
Menu flashes then exits

### ISSUE THREAD

**Issue by Shoot** [kgns/weapons#126]
Hello. I'm trying to type in the `!knife` command, or any other related command, but the menu only comes up for a very short amount of time, not even a second. If I spam the button I can still change my knife, but the menu disappears very quickly, making it inconvenient to use.
I'm using the latest version of this plugin with the latest PTAH (1.1.1) and the latest versions of SourceMod/MetaMod. In my `core.cfg` file I have the "FollowCSGOServerGuidelines" set to "no".

Edit:
I’m using Linux, and I’ve also noticed that this sometimes happens when typing !map in chat, so this may be an error with SM itself.

**Comment by kgns** [comment]
unrelated to this plugin
