### ISSUE TITLE
[REQUEST] Glow Skins

### ISSUE THREAD

**Issue by BlackYuzia** [kgns/weapons#128]
@kgns I have **question-request** about `skins`.

I find this video [https://youtu.be/aEWs631WPXM?t=525] (attached timeline)
Here (some cheater :eyes:) show us skins with LUA update. 
Cheat was modify (or change or etc) skins and they stay was better. (Glow or something like this)

Did we (U @kgns ) can do the same?

#### Examples:

![image](https://user-images.githubusercontent.com/25010528/68395336-2ebc0a00-0178-11ea-8f3b-4a63d5228a45.png)
![image](https://user-images.githubusercontent.com/25010528/68395377-44c9ca80-0178-11ea-9481-6f025a95ee89.png)
![image](https://user-images.githubusercontent.com/25010528/68395391-4eebc900-0178-11ea-9414-70097494041b.png)
![image](https://user-images.githubusercontent.com/25010528/68395414-57440400-0178-11ea-9c72-4920a33fbf3a.png)
![image](https://user-images.githubusercontent.com/25010528/68395456-66c34d00-0178-11ea-98b0-ee9a7c6589aa.png)
![image](https://user-images.githubusercontent.com/25010528/68395485-78a4f000-0178-11ea-8628-94b3954b834b.png)
![image](https://user-images.githubusercontent.com/25010528/68395516-822e5800-0178-11ea-9be0-8df6d72a8612.png)
![image](https://user-images.githubusercontent.com/25010528/68395527-8a869300-0178-11ea-809a-0f1aecfa4b0f.png)
![image](https://user-images.githubusercontent.com/25010528/68395546-92463780-0178-11ea-9325-0479f1d3c3ca.png)

**Comment by zhellqq** [comment]
No

**Comment by kgns** [comment]
well, @zhellqq gave the short answer

and a medium answer is that you cannot do this on the server-side

for the long answer you have to do your own research :)
