### ISSUE TITLE
Weapons & Knifes plugin not finding config files

### ISSUE THREAD

**Issue by ukiyoo1** [kgns/weapons#129]
`weapons.smx (Weapons & Knives): Could not find a config file for any languages.`
I have moved all the translations and cfg files (Including all of the ones with languages) into the csgo .cfg itself, and the cfg folder in sourcemods folder.

Please help (New to csgo servers pls be gentle)

**Comment by ukiyoo1** [comment]
Nevermind I realized that the cfg files were just in the configs folder itself, and not in the subfolder specified by the plugin

**Comment by Piti69** [comment]
Hello, i have the same error, how can i solve it?
