### ISSUE TITLE
[Request] [New Skins] Add new skin from last CSGO Update

### ISSUE THREAD

**Issue by BlackYuzia** [kgns/weapons#131]
Update: https://blog.counter-strike.net/index.php/2019/11/26310/

New Knifes classes:
>weapon_knife_cord
>weapon_knife_canis
>weapon_knife_outdoor

**Comment by Diam0ndz** [comment]
You missed the skeleton knife, weapon_knife_skeleton

https://github.com/kgns/weapons/pull/133

**Comment by LubricantJam** [comment]
Any date as of when you'll get round to this @kgns ?

**Comment by meciarsam** [comment]
I would like to know that aswell.

**Comment by d0kt0r** [comment]
please update the plugin for the latest skins

**Comment by supernoob180799** [comment]
how to get the smx file or the plugin of this?
please add!

**Comment by kgns** [comment]
check v1.5.0 release
