### ISSUE TITLE
Weird Crash at player spawn.

### ISSUE THREAD

**Issue by kurozavar** [kgns/weapons#136]
client.cpp (2647) : Assertion Failed: pHost && *pHost
httpclient.cpp (2647) : Assertion Failed: pHost && *pHost
crash_20191120075901_16.dmp[18414]: Uploading dump (out-of-process)
/tmp/dumps/crash_20191120075901_16.dmp
crash_20191120075901_16.dmp[18414]: Finished uploading minidump (out-of-process): success = no
crash_20191120075901_16.dmp[18414]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20191120075901_16.dmp[18414]: file ''/tmp/dumps/crash_20191120075901_16.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
ConVarRef sv_voice_proximity_minvolume doesn't point to an existing ConVar
Tried to look up command TIMELEFT as if it were a variable.
L 11/20/2019 - 07:59:10: "DɆX₮ɆR<4><STEAM_1:0:4000000002>" switched from team <Unassigned> to <TERRORIST>
L 11/20/2019 - 07:59:10: World triggered "Game_Commencing"
Wrote minidump to: /home/csgoserver/sv3serverfiles/csgo/addons/sourcemod/data/dumps/c7d5d86a-c3a7-470b-d7498fbd-2ae1210a.dmp
./srcds_run: line 318: 18378 Segmentation fault      $HL_CMD
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Wed Nov 20 07:59:10 EST 2019: Server restart in 10 seconds

[csgoserve 0:sh*                                         "delta" 07:59 20-Nov-19

I went about checking everything, making a new database. This happen after the new cs;go update yesterday.
Funny thing is that when weapons.smx is removed it stops crashing. (Also tried compiling it myself with no errors at all.) Any help will be appreciated.

**Comment by ByKyTa** [comment]
What your version ptah ?

**Comment by kurozavar** [comment]
Its the newest, i checked few times.

**Comment by paulocrash** [comment]
Have you updated your SourceMod to the latest version?

Remember to update the following plugins:
- SourceMod
- PTaH
- Weapons & Knives

And for security check that your server is also updated to the latest.

Also remember to strictly follow the installation mode:

> Use this without a GSLT token (LAN server), or use a token service for your servers, or your account will be banned from operating game servers, and a month cooldown from playing the game.
> Edit csgo/addons/sourcemod/configs/core.cfg => Change "FollowCSGOServerGuidelines" "yes" to "no"

**Comment by kurozavar** [comment]
Thanks for the advice, i will follow up tonight with results, please do not close the issue yet i will run some tests and let you know how it went.

**Comment by kgns** [comment]
try enabling GOTV

**Comment by kurozavar** [comment]
GOTV is always enabled

**Comment by kurozavar** [comment]
Yep, just tested and confirmed, updating sourcemod properly and following the instructions listed above made the plugin work just perfect.

Thank you for your patience and again im deeply sorry for my stupidity.
Great work!
