### ISSUE TITLE
Everything works except saving new knives into db

### ISSUE THREAD

**Issue by Erik-97** [kgns/weapons#138]
SM 1.10 - 6455
PTaH Extension V1.1.1-build16 Linux
Any solution to fix it?

L 11/20/2019 - 19:54:24: [SM] Exception reported: Error fetching data from field 311
L 11/20/2019 - 19:54:24: [SM] Blaming: weapons.smx
L 11/20/2019 - 19:54:24: [SM] Call stack trace:
L 11/20/2019 - 19:54:24: [SM]   [0] DBResultSet.FetchInt
L 11/20/2019 - 19:54:24: [SM]   [1] Line 66, weapons/database.sp::T_GetPlayerDataCallback

**Comment by kgns** [comment]
do you use MySQL or SQLite?

**Comment by Erik-97** [comment]
yeah im using MySQL and i tried to add manually the missing columns it was like 4 missing stuff for skeleton knive and a knive completely missing, its not solving the problem but maybe because they are not in order i think.
here is some useful info and the db download link.

https://www.mediafire.com/file/luhvqd9b8zs5tys/weapons.sql/file

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.28 - MySQL Community Server (GPL)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

Apache/2.4.29 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.2.24-0ubuntu0.18.04.1

Version information: 4.6.6deb5

**Comment by Erik-97** [comment]
yeah im using MySQL and i tried to add manually the missing columns(it was after i got this problem, before i didn't add them into db) it was like 4 missing stuff for skeleton knive and a knive completely missing, its not solving the problem but maybe because they are not in order i think.
here is some useful info and the db download link.

https://www.mediafire.com/file/luhvqd9b8zs5tys/weapons.sql/file

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.28 - MySQL Community Server (GPL)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

Apache/2.4.29 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.2.24-0ubuntu0.18.04.1

Version information: 4.6.6deb5

EDIT(2019.11.21 9:40)
these were the missing columns i added when i found out these are missing, but still not working
knife_canis_seed int(10) NOT NULL DEFAULT '-1',
knife_canis_tag varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
knife_canis_trak int(1) NOT NULL DEFAULT '0',
knife_canis_trak_count int(10) NOT NULL DEFAULT '0',
knife_skeleton_float decimal(3,2) NOT NULL DEFAULT '0.00',
knife_skeleton_seed int(10) NOT NULL DEFAULT '-1',
knife_skeleton_tag varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
knife_skeleton_trak int(1) NOT NULL DEFAULT '0',
knife_skeleton_trak_count int(10) NOT NULL DEFAULT '0'

**Comment by Erik-97** [comment]
Okay, the problem was the plugin adding the columns in the wrong order in the database so I tested to drop the new knives columns first and start the server but again it was added in the wrong order so I shut down my server and dropped all the columns and readded them with the help of weapons/database.sp and now everything works fine. Here is the solution and I think other people suffer from this problem.

ALTER TABLE weapons
DROP COLUMN knife_cord,
DROP COLUMN knife_cord_float,
DROP COLUMN knife_cord_trak,
DROP COLUMN knife_cord_trak_count,
DROP COLUMN knife_cord_tag,
DROP COLUMN knife_cord_seed,
DROP COLUMN knife_outdoor,
DROP COLUMN knife_outdoor_float,
DROP COLUMN knife_outdoor_trak,
DROP COLUMN knife_outdoor_trak_count,
DROP COLUMN knife_outdoor_tag,
DROP COLUMN knife_outdoor_seed,
DROP COLUMN knife_canis,
DROP COLUMN knife_canis_float,
DROP COLUMN knife_canis_trak,
DROP COLUMN knife_canis_trak_count,
DROP COLUMN knife_canis_tag,
DROP COLUMN knife_canis_seed,
DROP COLUMN knife_skeleton,
DROP COLUMN knife_skeleton_float,
DROP COLUMN knife_skeleton_trak,
DROP COLUMN knife_skeleton_trak_count,
DROP COLUMN knife_skeleton_tag,
DROP COLUMN knife_skeleton_seed,
ADD knife_cord int(4) NOT NULL DEFAULT '0',
ADD knife_cord_float decimal(3,2) NOT NULL DEFAULT '0.0',
ADD knife_cord_trak int(1) NOT NULL DEFAULT '0',
ADD knife_cord_trak_count int(10) NOT NULL DEFAULT '0',
ADD knife_cord_tag varchar(256) NOT NULL DEFAULT '',
ADD knife_cord_seed int(10) NOT NULL DEFAULT '-1',
ADD knife_canis int(4) NOT NULL DEFAULT '0',
ADD knife_canis_float decimal(3,2) NOT NULL DEFAULT '0.0',
ADD knife_canis_trak int(1) NOT NULL DEFAULT '0',
ADD knife_canis_trak_count int(10) NOT NULL DEFAULT '0',
ADD knife_canis_tag varchar(256) NOT NULL DEFAULT '',
ADD knife_canis_seed int(10) NOT NULL DEFAULT '-1',
ADD knife_outdoor int(4) NOT NULL DEFAULT '0',
ADD knife_outdoor_float decimal(3,2) NOT NULL DEFAULT '0.0',
ADD knife_outdoor_trak int(1) NOT NULL DEFAULT '0',
ADD knife_outdoor_trak_count int(10) NOT NULL DEFAULT '0',
ADD knife_outdoor_tag varchar(256) NOT NULL DEFAULT '',
ADD knife_outdoor_seed int(10) NOT NULL DEFAULT '-1',
ADD knife_skeleton int(4) NOT NULL DEFAULT '0',
ADD knife_skeleton_float decimal(3,2) NOT NULL DEFAULT '0.0',
ADD knife_skeleton_trak int(1) NOT NULL DEFAULT '0',
ADD knife_skeleton_trak_count int(10) NOT NULL DEFAULT '0',
ADD knife_skeleton_tag varchar(256) NOT NULL DEFAULT '',
ADD knife_skeleton_seed int(10) NOT NULL DEFAULT '-1';

UPDATE `weapons` SET `knife` = '0' WHERE `weapons`.`knife` <> '0';

**Comment by kgns** [comment]
we investigated this with @Erik-97, it turns out his mysql server is too slow, and while the plugin tried to create new columns (takes a few seconds for most, more than minutes for really slow mysql servers), his server crashed, which messed the column order up. he had to manually fix it. for anyone experiencing same problem, just reset your database or use a new one.

**Comment by GTAmama16** [comment]
@Erik-97 
im having the same issues here, can i add ur discord for help?
cnat rly understand how to fix it :(

**Comment by Erik-97** [comment]
> @Erik-97
> im having the same issues here, can i add ur discord for help?
> cnat rly understand how to fix it :(

Er!k#2952
or steam
https://steamcommunity.com/id/Erik-97/
