### ISSUE TITLE
Don't see updated list

### ISSUE THREAD

**Issue by mmendesico** [kgns/weapons#139]
I updated all possible files that needed to be, and could not succeed in the new skins, because they do not appear in the list, only the skins listed until the update of the boxes of 20 years. Could kindly give a guide on this problem?

**Comment by AkalaGit** [comment]
Same issue.

**Comment by AkalaGit** [comment]
I had the same issue but fixed it by updating PTaH.

https://ptah.zizt.ru/

**Comment by kgns** [comment]
i dont understand what the problem actually is, can you send some screenshots?

**Comment by mmendesico** [comment]
@AkalaGit I found it strange because I also updated PtaH to the last update and kept giving the same problem without updating the list.

**Comment by mmendesico** [comment]
> i dont understand what the problem actually is, can you send some screenshots?

@kgns Even updated, the list still retains the previous version and not the current one.

**Comment by kgns** [comment]
can you upload some screenshots?

**Comment by mmendesico** [comment]
Pode fechar o artigo do problema, não estava compilando na pasta com a PaTH atualizada.. Erro bem besta meu.. Valeu! @kgns

**Comment by kgns** [comment]
i guess it was a compile problem? thats what google translate tells me.

**Comment by mmendesico** [comment]
Yes, only problem was the compilation.

**Comment by kgns** [comment]
next time, please do not open an issue here if you are using your own version of the plugin that you compiled. first make sure to test your problem with the official release binary from the repository. if you dont encounter the problem with the official binary, then its a sign that you messed something up. if it persists, then open an issue here. thanks
