### ISSUE TITLE
[REQ] Adding pearlescent value

### ISSUE THREAD

**Issue by z4cH3r** [kgns/weapons#140]
Hey, i saw valve added a new value for pearlescent effect, asking if you can add it.

More info here https://youtu.be/0RoeSMlwywE

Thanks!

**Comment by BlackYuzia** [comment]
@z4cH3r if I remember right.

This is work only on SDK side.
So, plugin can't change materials of weapons skins. :thinking:

**Comment by kgns** [comment]
if this is something like weapon wear (float), and the netvar for it is there, it can be added in the future. if its set in while making the skin (i.e. every skin has the same value of it), then it cannot be changed in-game. will close this request, but I will keep on checking for future developments on the issue
