### ISSUE TITLE
knives skin wont be saved 

### ISSUE THREAD

**Issue by GTAmama16** [kgns/weapons#141]
so after i install the latest release, ppl in my server are saying that when they pick a new knife skin and after they quit and rejoin the server, the server wont save their skin, im using the latest SM version and MySQL, no error when i type sm plugins list in console, can u plz check whats going on ?

thanks

**Comment by kgns** [comment]
you either didnt wait enough for the new columns to be generated, or had a server crash while them being generated. delete your database and start anew

**Comment by GTAmama16** [comment]
thanks to erik for the help issues resolved :D
