### ISSUE TITLE
Plugin doesn’t work on a Ubuntu box.

### ISSUE THREAD

**Issue by AkalaGit** [kgns/weapons#142]
(I’m using LGSM to manage the server and haven’t setup a CS:GO server before on Ubuntu.)

I’ve installed source mod properly it works just fine, Splewis’ Get5 plugin runs fine on the server as well but Gloves and Weapons don’t. I wanted to know if it’s a PTaH issue, an issue on my end (maybe I’m doing something wrong), or if PTaH/the plugins don’t work on Ubuntu. I’m using the latest Linux version of PTaH btw.

**Comment by kgns** [comment]
send logs and information

and generally plugins have nothing to do with OS version, if it doesnt work, its not because of an operating system or version

**Comment by AkalaGit** [comment]
I'll send them asap

**Comment by AkalaGit** [comment]
I think it's because of the way I've been installing the plugin. I've been downloading the plugin to my Windows machine to configure it and then I move them over to the Ubuntu box and when starting the server I get a permissions error so I do "chown -R csgoserver:csgoserver /home/csgoserver/" and then the server loads just fine. Although, after starting the server the commands "!ws" and "!knife" don't work. I've also tried to load the plugin while the server was running with "sm plugins load weapons" and that doesn't work either.

Here's the error log (seems like PTaH is the issue? I thought it was the way I was moving the files over.):
L 11/28/2019 - 06:21:07: SourceMod error session started
L 11/28/2019 - 06:21:07: Info (map "de_cache") (file "errors_20191128.log")
L 11/28/2019 - 06:21:07: [SM] Failed to load plugin "gloves.smx": Unable to load plugin (no debug string table).
L 11/28/2019 - 06:21:07: [SM] Unable to load extension "PTaH.ext": Could not find interface: ISourceMod
L 11/28/2019 - 06:21:07: [SM] Unable to load plugin "weapons.smx": Required extension "PTaH" file("PTaH.ext") not running
L 11/28/2019 - 06:21:16: Error log file session closed.
L 11/28/2019 - 06:21:16: SourceMod error session started
L 11/28/2019 - 06:21:16: Info (map "de_cache") (file "errors_20191128.log")
L 11/28/2019 - 06:21:16: [SM] Failed to load plugin "gloves.smx": Unable to load plugin (no debug string table).
L 11/28/2019 - 06:22:22: Error log file session closed.
L 11/28/2019 - 06:26:02: SourceMod error session started
L 11/28/2019 - 06:26:02: Info (map "de_cache") (file "errors_20191128.log")
L 11/28/2019 - 06:26:02: [SM] Failed to load plugin "gloves.smx": Unable to load plugin (no debug string table).
L 11/28/2019 - 06:26:02: [SM] Unable to load extension "PTaH.ext": Could not find interface: ISourceMod
L 11/28/2019 - 06:26:02: [SM] Unable to load plugin "weapons.smx": Required extension "PTaH" file("PTaH.ext") not running
L 11/28/2019 - 06:26:18: Error log file session closed.
L 11/28/2019 - 06:26:18: SourceMod error session started
L 11/28/2019 - 06:26:18: Info (map "de_cache") (file "errors_20191128.log")
L 11/28/2019 - 06:26:18: [SM] Failed to load plugin "gloves.smx": Unable to load plugin (no debug string table).
L 11/28/2019 - 06:27:36: Error log file session closed.

**Comment by kgns** [comment]
as I suspected, sourcemod and its extension files differ for windows and linux. you have to use linux files for it to work (not .dll files, use .so files)

**Comment by AkalaGit** [comment]
Does the Weapons or or Gloves plugin have .so versions of the .dlls?

**Comment by AkalaGit** [comment]
Or is there a way to make them Linux compatible?

**Comment by AkalaGit** [comment]
I have Splewis' Get5 running on the server with no issues btw.

**Comment by kgns** [comment]
plugins do not have .dll or .so files, only sourcemod itself and its extensions like PTaH have them. your problem is that you are not installing the correct OS version of PTaH...

**Comment by AkalaGit** [comment]
I installed the latest version of PTaH for Linux. I’ve double checked and
it’s the right one.

**Comment by AkalaGit** [comment]
Should I try an older version of PTaH?

**Comment by kgns** [comment]
"[SM] Unable to load extension "PTaH.ext": Could not find interface: ISourceMod"
you should get help from sourcemod people or PTaH extension people. as I said, these problems are not related to this plugin.
