### ISSUE TITLE
[1] Line 37, weapons/hooks.sp::GiveNamedItemPre

### ISSUE THREAD

**Issue by megoRU** [kgns/weapons#143]
L 11/23/2019 - 16:47:33: [SM] Exception reported: Array index out-of-bounds (index 49, limit 49)
L 11/23/2019 - 16:47:33: [SM] Blaming: weapons.smx
L 11/23/2019 - 16:47:33: [SM] Call stack trace:
L 11/23/2019 - 16:47:33: [SM]   [1] Line 37, weapons/hooks.sp::GiveNamedItemPre

**Comment by kgns** [comment]
use the released smx file.

**Comment by megoRU** [comment]
@kgns where take released smx file.
