### ISSUE TITLE
weapons plugin can't work with SQLite

### ISSUE THREAD

**Issue by ZZHLMY** [kgns/weapons#146]
Hello, I find some bug in weapons plugin, this plugin can't work with SQLite

**Comment by kgns** [comment]
not enough information, please supply more

**Comment by ZZHLMY** [comment]
If I work the plugin in my pc and use SQLite, when I choose a skin, it can't change to my choice

**Comment by kgns** [comment]
still, not enough information. if you want this issue to be taken seriously, provide information and logs that will be useful in deciding whether its really a bug or not

**Comment by kgns** [comment]
if you want to send more information, feel free to reopen this issue, otherwise i don't think there are any problems with SQLite usage
