### ISSUE TITLE
is it possible to readd the choose all skin option?

### ISSUE THREAD

**Issue by GTAmama16** [kgns/weapons#147]
so i was trying to re add the all skin option and im just wondering is it possible to do it by myself?
havent modifying any .sp file before, so is it possible to do it ? 

thanks

**Comment by kgns** [comment]
edit configs/weapons/weapons_xxx.cfg files, add every weapon for every ID like:
"weapon_m4a1;weapon_ak47;weapon_knife_karambit;......."

**Comment by GTAmama16** [comment]
Thanks, so I saw that u delete some code from the .sp file, if I re add the code and modify the .cfg file will it work ?

**Comment by kgns** [comment]
do not touch the .sp

**Comment by GTAmama16** [comment]
ok thanks for the reply
