### ISSUE TITLE
Error Log!!

### ISSUE THREAD

**Issue by Drmohammad11** [kgns/weapons#148]
hi!!
i used last version and i see this error on logs:

L 11/28/2019 - 00:00:04: SourceMod error session started
L 11/28/2019 - 00:00:04: Info (map "de_dust2") (file "C:\ToosGame-Servers\01-Public\csgo\addons\sourcemod01\logs\errors_20191128.log")
L 11/28/2019 - 00:00:04: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:213019934')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:01:00: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:194065888')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:01:30: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:225048787')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:03:08: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:219609910')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:04:22: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:105794629')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:04:51: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:487970280')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:04:53: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:522318060')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:05:44: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:520687922')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:07:37: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:432727052')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:10:09: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:223909188')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:11:47: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:514713855')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:12:03: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:418645041')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:14:13: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:1099720')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:14:52: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:168607894')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:16:28: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:107106634')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:16:48: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:505403878')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:17:56: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:137788838')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:19:27: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:125799715')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:22:25: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:495325049')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:24:08: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:241241100')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:27:12: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:149990535')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:31:33: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:501916243')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:31:48: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:93483885')" error: "UNIQUE constraint failed: weapons.steamid"
L 11/28/2019 - 00:34:45: [Addons_weapons_skin.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:211189113')" error: "UNIQUE constraint failed: weapons.steamid"

**Comment by BlackYuzia** [comment]
In DB already exist this SteamID's. (Why plugin try add sid's to db again - I didn't know)

You can try delete DB and restart server.
Or, if u didn't want do it, wait a developer of plugin. :thinking:

**Comment by Drmohammad11** [comment]
> In DB already exist this SteamID's. (Why plugin try add sid's to db again - I didn't know)
> 
> You can try delete DB and restart server.
> But, if u didn't want do it, wait a developer of plugin.

i do but dont work!!
