### ISSUE TITLE
Cannot choose knife

### ISSUE THREAD

**Issue by iEzCnF** [kgns/weapons#149]
I cannot choose knife, appears in white colour and when i press the 2 key doesnt do anything

**Comment by kgns** [comment]
more info needed

**Comment by iEzCnF** [comment]
I send a screenshot 
![Screenshot_29](https://user-images.githubusercontent.com/20783297/69830791-b56b8080-1226-11ea-8663-c956b41e2a7b.png)
The knife color is different, i dont know if that has anything with my problem but when i select it with the number 2 on the keyboard it doesnt do anything

**Comment by Wyll3R** [comment]
Try !knife and then !ws

**Comment by kgns** [comment]
as @Wyll3R said, you have to get a knife that is not default knife first to be able to use skins on it. default knife does not have any skins
