### ISSUE TITLE
TTT Ground Weapons don't skin.

### ISSUE THREAD

**Issue by LubricantJam** [kgns/weapons#156]
On my TTT server, weapons picked up from the ground aren't skinned. I have enabled the other weapons cvar and no luck. Is it the way they're picked up from the map?

**Comment by kgns** [comment]
picked up weapons were never covered in this plugin. you wouldnt have those map weapons skinned even when you have the real weapon skins in your inventory, and i like to keep things as close as possible to the real thing

**Comment by LubricantJam** [comment]
> picked up weapons were never covered in this plugin. you wouldnt have those map weapons skinned even when you have the real weapon skins in your inventory, and i like to keep things as close as possible to the real thing

Understandable but it kinda renders the plugin useless on TTT servers then?

**Comment by kgns** [comment]
well, TTT servers render the whole real weapon skin ecosystem useless on its own too then :)

**Comment by LubricantJam** [comment]
I can understand your point but it's just community servers are different from the "real thing" especially when it's not a liked to add-on by Valve.

**Comment by kgns** [comment]
yes but i dont want to take a different path with this plugin. weapon skins, player agents etc. are already making this game childish, i dont want to make it anymore arcade game if you know what i mean, sorry. you can always add the functionality yourself though

**Comment by LubricantJam** [comment]
No worries! Could you point me in the right direction as to where I'd most likely be able to make it happen? I've got ample SM knowledge but not the best!

**Comment by kgns** [comment]
setting skin details function is already there, you just need to find the best event to hook into (weapon pickup), check if its a no-skin map weapon, and call the refreshweapon function. should be easy

**Comment by LubricantJam** [comment]
Yep, I know exactly what you're on about, cheers! :)
