### ISSUE TITLE
How to customize the order to change skins?

### ISSUE THREAD

**Issue by HibarigaokaRuri** [kgns/weapons#157]
I want to change the default command typed in chat "!knife" or "/knife" into other command. Because the full ten plugin have a command /knife to enable the knife round. That will cause knife skin menu doesn't show up. So I want to change the command. How to do this? Thank you!

**Comment by flashing1998** [comment]
you have to edit the source code for it

**Comment by kgns** [comment]
https://github.com/kgns/weapons/blob/1490814d154c4c2122fc988a6b558a188ecd8702/addons/sourcemod/scripting/weapons.sp#L80

edit here and compile the plugin yourself
