### ISSUE TITLE
weapon plugin and gloves not working {!ws, !knife & !gloves}

### ISSUE THREAD

**Issue by rigller** [kgns/weapons#159]
I downloaded all the !ws and !gloves plugin but there is no skins visible in the game.
neither the skins are changing and when i changing gloves the player arms goes invisible, i am not using any custom model and the server is fresh with no other plugins except yours. i have installed the ptaH files as well.

i get all the options of !ws and !kinfe but skins dont showup and only basic knife models are visible.

**Comment by kgns** [comment]
make sure to follow all the installation instructions carefully, this is just a bad install

**Comment by ghost** [comment]
He's right. It's not working.
