### ISSUE TITLE
Glitch issue with knife of maps

### ISSUE THREAD

**Issue by EG-DEVIL** [kgns/weapons#160]
Hello!
A player on my server showed me this glitch so I report it to you.
You can become invisible, loose your hitbox if you use !knife or !ws after you got a knife placed on a map. This happened on a Zombie Escape server.

Here is the video showing the bug: https://www.youtube.com/watch?v=8j5MntPDYqU

Is it possible to disable the commands if a player has a map knife ?

Thanks.

**Comment by kgns** [comment]
this is not related to !ws !knife plugin. you should ask the owner of whichever plugin OR map (entity) is causing the issue to fix it on their end
