### ISSUE TITLE
Server crash when closing menu while being displayed

### ISSUE THREAD

**Issue by stickz** [kgns/weapons#163]
The following line in `config.sp` triggers a server crash. 
https://github.com/kgns/weapons/blob/c0fed5166a1fc2fb45dfc17e3cde85b794b1c3b8/addons/sourcemod/scripting/weapons/config.sp#L62

You can't close a menu when it's currently being displayed. 

Here is the server crash report.
https://crash.limetech.org/3gj2hso42pdf

Here is the link to the sourcemod issue.
https://github.com/alliedmodders/sourcemod/issues/1047

**Comment by stickz** [comment]
Also gloves from anther repo does the same thing.
https://github.com/kgns/gloves/blame/7447d12bef1899fb8a29903bc1f33dc854c3cafc/addons/sourcemod/scripting/gloves/config.sp#L54

**Comment by kgns** [comment]
that line cannot crash the server. its backed up with an if check to control that it is not null before using delete on it, also that is the only line that tries to delete the Menu Handle (so "You have a bad plugin freeing a menu twice" comment from the sourcemod github issue does not apply here). also the crash you are having seems to be specific to you only, as accelerator logs say "2 reports share this crash signature. (1 owner / 1 ip)"

**Comment by dragokas** [comment]
You can walkaround the problem by tracking whether your menu handle is in use at the moment (it's can be easily accomplished with menu handler + additional bool array[client] = handle ).

Helper function will test for "in use" and call menu closing code for every affected clients:
```
InternalShowMenu(client, "\10", 1);
```

**Comment by kgns** [comment]
this was resolved on sourcemod discord server, it turns out there was a faulty plugin installed on his server causing the crashes, and the issue was unrelated to weapons plugin

![image](https://user-images.githubusercontent.com/1769694/76584742-a5359380-64ed-11ea-9eda-21cc05b03d13.png)
