### ISSUE TITLE
!ws menu dissapearing instantly after it opens

### ISSUE THREAD

**Issue by aartyx** [kgns/weapons#167]
I installed the v1.6.0 weapons files, they seem to work, but the !ws and !knife menu instantly dissapears right after opening it.. 
Changed BlockBadPlugins and FollowCSGOServerGuidelines "yes" --> "no", still the same.

**Comment by Cruze03** [comment]
Check error logs

**Comment by kgns** [comment]
its either an error on your side, or an incompatible plugin that you use. not an issue with this plugin
