### ISSUE TITLE
Feature request: Can I get different knife when I play T or CT?

### ISSUE THREAD

**Issue by Yuze0101** [kgns/weapons#168]
I use your plugins gloves weapons for a long time.Thanks your hard work~
Gloves has different choise ：CT or T.
I hope weapons also has this function.I mean !knife has this function.

**Comment by crashzk** [comment]
It would be very welcome, both for the option of knives and for skins too. Perfect if you have the option for players to choose both the knife for each side, as well as the skins.

**Comment by RoyZ-CSGO** [comment]
check bone's version https://github.com/BoneTM/weapons
