### ISSUE TITLE
Have more than one knives

### ISSUE THREAD

**Issue by turkcodec** [kgns/weapons#174]
Hello,

When you didnt die and the next rounds you have more than one knives.

Can you help me about it?

Thank you very much.

**Comment by DiegoNascimento1** [comment]
What?

Em dom, 10 de mai de 2020 21:11, turkcodec <notifications@github.com>
escreveu:

**Comment by turkcodec** [comment]
I use this plugin and when you didnt die and next round you start with many knives.

**Comment by kgns** [comment]
#150
