### ISSUE TITLE
Issue with skins for VAC Banned accounts

### ISSUE THREAD

**Issue by Nevvy** [kgns/weapons#179]
Version: 1.6.0
PTAH: V1.1.1-build17
Issue: Skins are not visible for players with CSGO VAC bans on their accounts. 
Non Banned & Overwatch Banned acounts are fine
![test](https://user-images.githubusercontent.com/39029600/83886613-999de580-a747-11ea-9f39-5dc61508b8f5.png)

**Comment by UWPA** [comment]
Are you sure the Texture Streaming option isn't enabled? That causes issues with this. Also make sure they don't have a skin changer from their cheat. I use a vacced account and it shows the skins perfectly fine.

**Comment by Nevvy** [comment]
Well, i was not injected at all. Ill check Texture Streaming in my config

**Comment by Nevvy** [comment]
After disabling texture streaming all works
