### ISSUE TITLE
Does not work correctly. After the last update CS:GO

### ISSUE THREAD

**Issue by gg-cfg** [kgns/weapons#180]
Hello everybody! after the last update of the game, the plugin did not work correctly!
![20200606160215_1](https://user-images.githubusercontent.com/20066996/83947064-6463c700-a81d-11ea-8cad-a5804cb47932.jpg)

**Comment by UWPA** [comment]
Disable Texture Streaming in your Game settings.

**Comment by RusJJ** [comment]
Now we need to find a fix... :(

**Comment by GSNotifications** [comment]
Disable texture streaming.

**Comment by RusJJ** [comment]
Really? WHOA

**Comment by kgns** [comment]
Disable texture streaming
