### ISSUE TITLE
Weapon/Knife Dissapears when using !ws, only can be used and seen after death

### ISSUE THREAD

**Issue by roygeorgekala** [kgns/weapons#182]
When i use the !ws command and change a skin on the knife or the weapon, I stop holding it and then right after i switch to another gun it dissapears. I cant use it or see it until next spawn . 
![Annotation 2020-07-22 191653](https://user-images.githubusercontent.com/45360115/88184113-f3069900-cc4f-11ea-8db2-a9a9b0a6f662.jpg)

**Comment by kgns** [comment]
Check your server console for any exceptions. It seems that when the plugin tries to refresh your weapon (remove current one and give a new one), it fails to give you a new weapon. This should not happen if you are not using a modified plugin, or if you have configured your server and the plugin correctly
