### ISSUE TITLE
unable to open file [BUG]

### ISSUE THREAD

**Issue by 7ancy** [kgns/weapons#184]
![QQ图片20200730175705](https://user-images.githubusercontent.com/64363457/88909772-19e74f80-d28e-11ea-9ee8-930621c83a60.png)

File permissions are OK, running on the windows server
After the restart, it works normally, but after running for a period of time, the plugin cannot be used、

 P Tools and Hooks V1.1.2-build18 windows

**Comment by kgns** [comment]
this is an issue of your server configuration certainly, not a bug with this plugin

**Comment by 7ancy** [comment]
can you tell me How can I fix it

**Comment by kgns** [comment]
https://forums.alliedmods.net/showthread.php?t=245251
https://forums.alliedmods.net/showthread.php?t=307953

pick your poison :)
