### ISSUE TITLE
Freeze Server

### ISSUE THREAD

**Issue by ZakharYA** [kgns/weapons#185]
Hello, after installing the plugin, the server freezes after a while.
(The server is not available, the console is the same).
Before the server freeze, it was written in the logs: 

> [weapons.smx] Inactive players' data has been deleted

SM Version: 1.10.0.6492
PTaH: 1.1.2
OC: Linux

1. sm plugins list

> [SM] Listing 105 plugins:
>   001 "[ Menu Creator ]" (3.0.0.1) by AlexTheRegent
>   002 "Fun Votes" (1.10.0.6477) by AlliedModders LLC
>   003 "[HS] Запись демо" (2.2.5) by mukunda & hiskill
>   004 "SourceTV / GOTV Protector" (1.0) by CrazyHackGUT aka Kruzya
>   005 "[HS] Онлайн" (1.0)
>   006 "Special Team Balancer" (0.5.0) by AlmazON
>   007 "Terrible Enable Full Alltalk" (0.02) by Sheepdude
>   008 "GameVoting.smx"
>   009 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
>   010 "Fun Commands" (1.10.0.6477) by AlliedModders LLC
>   011 "Server Clean Up _Xnet CS:GO" (1.2.2) by Jamster
>   012 "Weapon Restrict" (3.1.7) by Dr!fter
>   013 "Plugins Manager" (1.1) by CrazyHackGUT aka Kruzya
>   014 "[HS] Change Team" (1.0) by vk.com/planescraft
>   015 "The Void" (0.4) by SM9 (xCoderx) - FragDeluxe.com
>   016 "[HS] Админ чат" (1.00) by Klaus && HiSkill
>   017 "AFK Manager" (4.1.4) by Rothgar
>   018 "[HS] Система донатов" (1.1) by High SKILL
>   019 "[Levels Ranks] Core" (v3.1.2) by RoadSide Romeo & Wend4r
>   020 "Server redirect" (1.1) by GAMMA CASE, Rostu
>   021 "Basic Info Triggers" (1.10.0.6477) by AlliedModders LLC
>   022 "Thirdperson" (1.5) by shavit
>   023 "[HS] Timeleft on chat" (1.3) by High SKill
>   024 "Player Time Tracker (Redux)" (3.2.1) by namazso перевод by wilson.aka
>   025 "[Keys] Core" (1.4) by R1KO
>   026 "[Keys] VIP" (1.3) by R1KO
>   027 "[Keys] Shop" (1.1) by R1KO
>   028 "[HS][CS] Clan Core" (1.0) by High SKILL
>   029 "Player Commands" (1.10.0.6477) by AlliedModders LLC
>   030 "five_privet.smx"
>   031 "[HS] AWP Менеджер" (1.0)
>   032 "[HS] Менеджер аккаунтов" (1.1) by High SKill
>   033 "[MA] Advanced Functionality" (1.1.4) by OkyHp
>   034 "Basic Comm Control" (0.7.9) by AlliedModders LLC
>   035 "Material Admin" (0.7.9) by Material Admin Dev Team
>   036 "Resetscore+" (1.5.1) by AlmazON
>   037 "Connect Announce" (1.8) by Arg!
>   038 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
>   039 "REGEX word filter" (1.2) by Twilight Suzuka
>   040 "[HSUM] Логирование" (1.0) by High SKill
>   041 "HexProps" (1.53) by Hexah
>   042 "High Ping Kicker" (2.9) by Liam
>   043 "Basic Votes" (1.10.0.6477) by AlliedModders LLC
>   044 "Basic Chat" (1.9.0.6276) by AlliedModders LLC
>   045 "Client Preferences" (1.10.0.6477) by AlliedModders LLC
>   046 "Gloves" (1.0.3) by kgns | oyunhost.net
>   047 "[HS] Запрет низких рангов" (1.0) by HiSkill
>   048 "[HS] Fake Drop" (1.0.1) by Zakhar (https://vk.com/ghost1337gg)
>   049 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
>   050 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
>   051 "HotGuard AntiCheat" (3.2.1) by MaZa
>   052 "Admin Help" (1.10.0.6477) by AlliedModders LLC
>   053 "Knife choice CORE - Выбор ножа ЯДРО" (2.11) by Phoenix - Феникс
>   054 "Basic Commands" (1.10.0.6477) by AlliedModders LLC
>   055 "Admin Menu" (1.10.0.6477) by AlliedModders LLC
>   056 "Exploding Chickens" (1.5) by PeEzZ
>   057 "Реклама" (1.4) by Pheonix (‰7Феникс7‰)
>   058 "[Shop] Vampirism" (1.1) by R1KO
>   059 "[Shop] Logs" (1.2) by R1KO (skype: vova.andrienko1)
>   060 "[Shop] Equipments" (2.1.1) by FrozDark, modify by BaFeR
>   061 "[Shop] Double Jump" (1.1) by R1KO
>   062 "[Shop] Core" (3.0B8) by FrozDark (Fork by R1KO & White Wolf)
>   063 "[Shop] Top10 Function" (2.0.1) by FrozDark
>   064 "[Shop] Money Distributor" (1.4.3) by FrozDark (HLModders LLC)
>   065 "[HS] Спонсорство" (1.0B) by High SKILL
>   066 "[HS API] Core" (1.3) by Zakhar
>   067 "Map configs" (1.3) by Berni
>   068 "buffer.smx"
>   069 "[HS] Автобаланс команд V2" (1.00) by hiskill.ru
>   070 "[VIP] Vips Online" (1.0.1) by R1KO (skype: vova.andrienko1)
>   071 "[VIP] Regen HP" (1.0.4) by R1KO
>   072 "[VIP] Show Damage" (1.0.0) by R1KO
>   073 "[VIP] No Fall Damage" (1.0.0) by R1KO (skype: vova.andrienko1)
>   074 "[VIP] Base Functions" (1.3) by R1KO (skype: vova.andrienko1)
>   075 "[VIP] Defuser" (1.0.0) by R1KO (skype: vova.andrienko1)
>   076 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
>   077 "[VIP] Paint" (1.6) by asdf
>   078 "[VIP] CHAT (+scp)" (3.1.1) by R1KO
>   079 "[VIP] Покупка оружия команды" (1.2.3) by Planes
>   080 "[VIP] Anti Flash" (1.0.0) by R1KO
>   081 "[VIP] Extended Ammo" (1.10) by R1KO
>   082 "[VIP] Client Spawn Hook Fix" (1.0.1) by CrazyHackGUT aka Kruzya
>   083 "[VIP] Features Manager" (2.0 DEV) by R1KO
>   084 "[ViP Core]Jump effect/Эффект от прыжка" (1.3.0 (rewritten by Grey83)) by Nek.'a 2x2
>   085 "[VIP] MKIT" (1.1) by Pheonix (edit Felya)
>   086 "[VIP] Endurance" (1.0.0) by R1KO (skype: vova.andrienko1)
>   087 "[VIP] Core" (3.0 R) by R1KO
>   088 "[VIP] No Self Damage" (1.0.0) by R1KO (skype: vova.andrienko1)
>   089 "[VIP] Hook (PRIVATE)" (1.1) by R1KO
>   090 "[VIP] GrenadeTrails" (1.0.1) by R1KO
>   091 "[VIP] FastReload" (1.0) by BaFeR
>   092 "[VIP] Evade (Уворот)" (1.0) by Miaka (Ice_Sochi) & R1KO
>   093 "Files Management Interface" (1.0.2) by RedSword / Bob Le Ponge
>   094 "Simple Stealth" (1.0) by Potatoz
>   095 "Admin File Reader" (1.10.0.6477) by AlliedModders LLC
>   096 "[LR] Module - TOP by KDR" (v3.1) by Wend4r
>   097 "[LR] Module - ExStats Hits" (v3.1) by Wend4r
>   098 "[LR] Module - FakeRank" (v3.1) by RoadSide Romeo & Wend4r
>   099 "[LR] Module - Blue Screen Kill" (v3.1) by RoadSide Romeo & R1KO
>   100 "[LR] Module - ExStats Maps" (3.1 F1) by RoadSide Romeo
>   101 "[LR] Module - Calibration" (v3.1) by RoadSide Romeo
>   102 "[LR] Module - ExStats Weapons" (v3.1) by RoadSide Romeo & Wend4r
>   103 "[HS] Иконка стим игрока" (1.0) by High SKill
>   104 "[HS] Выдача оружия" (2.0.2) by HiSkill
>   105 "Anti-Flood" (1.10.0.6477) by AlliedModders LLC

2. sm exts list

> [SM] Displaying 17 extensions:
> [01] cURL Extension (1.3.0.0): cURL Extension
> [02] Accelerator (2.5.0): SRCDS Crash Handler
> [03] Webternet (1.10.0.6492): Extension for interacting with URLs
> [04] CS Tools (1.10.0.6492): CS extended functionality
> [05] BinTools (1.10.0.6492): Low-level C/C++ Calling API
> [06] SDK Tools (1.10.0.6492): Source SDK Tools
> [07] SDK Hooks (1.10.0.6492): Source SDK Hooks
> [08] Top Menus (1.10.0.6492): Creates sorted nested menus
> [09] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
> [10] Client Preferences (1.10.0.6492): Saves client preference settings
> [11] SQLite (1.10.0.6492): SQLite Driver
> [12] DHooks (2.2.0-detours10): Dynamic Hooks
> [13] Regex (1.10.0.6492): Provides regex natives for plugins
> [14] GeoIP (1.10.0.6492): Geographical IP information
> [15] GeoIPCity (1.1.2): Geographical IP information
> [16] PTaH (1.1.2): Additional CS:GO Hooks and Natives
> [17] MySQL-DBI (1.10.0.6492): MySQL driver implementation for DBI

**Comment by kgns** [comment]
I can't see weapons.smx file loaded in your plugins list. In fact there is "053 "Knife choice CORE - Выбор ножа ЯДРО" (2.11) by Phoenix - Феникс" which is probably not compatible with this plugin as they both do similar things and use PTaH hooks to modify data.

**Comment by ZakharYA** [comment]
Oh, good.
You can't see the plugin, because I unloaded it so that the server doesn't freeze.
I will try to remove the "053 "Knife choice CORE - Выбор ножа ЯДРО" (2.11) by Phoenix - Феникс" plugin, and unsubscribe with performance.

**Comment by ZakharYA** [comment]
The problem really was this plugin. Thank!
