### ISSUE TITLE
Stattrak not tracking

### ISSUE THREAD

**Issue by UWPA** [kgns/weapons#195]
Hi. When using Version 1.7.0 released 26 days ago the Stattrak doesn't update at all on weapons however on the PR Fix for 187 it updates on Client death or purchase of the weapon, is there a way to have the old functionality restored to where it was each round?

**Comment by kgns** [comment]
update SourceMod

**Comment by UWPA** [comment]
Sourcemod is on the latest, it's the same issue.

**Comment by kgns** [comment]
i doubt it, the hook that was used for stattrak increments was updated in the game and sourcemod changed some internal code for it. in the latest version of sourcemod the hook works, but not on the older versions

**Comment by UWPA** [comment]
As I said, the only way it "updates" is if you purchase the weapon again. This is on SM 1.10 and 1.11

**Comment by kgns** [comment]
that means stattrak feature is working... check the thread on alliedmods.net -> https://forums.alliedmods.net/showthread.php?t=298770

"StatTrak counts do not apply immediately after a kill, it will refresh when you get a new weapon."

**Comment by UWPA** [comment]
Why was it added to be like that, if you don't mind my asking?

**Comment by kgns** [comment]
live update was too much work for me back then and unnecessary, feel free to send a pull request. stattrak is working, unlike the issue title. you just need to read before you create issues :)
