### ISSUE TITLE
Server crashing after joining into server.

### ISSUE THREAD

**Issue by bboychris168** [kgns/weapons#196]
I am currently using both Gloves and Weapons plugins. Whenever i join a server it crashes. 
I disabled both Weapons.smx and Gloves.smx plugins and my servers are working fine. the only other plugin I am using is Get5 plugin by Splewis. The crashing occurs most of the time I used to have to restart the server for then to rejoin back in. But now it is happening so often that I had to disable the plugins. 

![image](https://user-images.githubusercontent.com/43663480/93619810-72300780-fa1c-11ea-8454-e17c716d7fea.png)

**Comment by bboychris168** [comment]
`L 09/19/2020 - 02:19:09: SourceMod error session started
L 09/19/2020 - 02:19:09: Info (map "de_dust2") (file "/home/dathost/csgo_ds/csgo/addons/sourcemod/logs/errors_20200919.log")
L 09/19/2020 - 02:19:09: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 09/19/2020 - 02:19:09: [SM] Blaming: weapons.smx
L 09/19/2020 - 02:19:09: [SM] Call stack trace:
L 09/19/2020 - 02:19:09: [SM]   [1] Line 69, tmp/addons/sourcemod/scripting/weapons/hooks.sp::ChatListener
L 09/19/2020 - 02:19:09: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 09/19/2020 - 02:19:09: [SM] Blaming: weapons.smx
L 09/19/2020 - 02:19:09: [SM] Call stack trace:
L 09/19/2020 - 02:19:09: [SM]   [1] Line 69, tmp/addons/sourcemod/scripting/weapons/hooks.sp::ChatListener
L 09/19/2020 - 02:19:09: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 09/19/2020 - 02:19:09: [SM] Blaming: weapons.smx
L 09/19/2020 - 02:19:09: [SM] Call stack trace:
L 09/19/2020 - 02:19:09: [SM]   [1] Line 69, tmp/addons/sourcemod/scripting/weapons/hooks.sp::ChatListener
L 09/19/2020 - 02:22:02: Error log file session closed.
L 09/19/2020 - 02:30:49: SourceMod error session started
L 09/19/2020 - 02:30:49: Info (map "de_mirage") (file "/home/dathost/csgo_ds/csgo/addons/sourcemod/logs/errors_20200919.log")
L 09/19/2020 - 02:30:49: [get5_eventapi.smx] API request failed, HTTP status code = 0
L 09/19/2020 - 02:30:49: [get5_eventapi.smx] x@��
L 09/19/2020 - 02:31:09: Error log file session closed.`

**Comment by shayota** [comment]
Did you ever find the solution? Having very similar behavior on my fresh server.

I'm thinking it stems from the sql databases not being configured correctly but haven't found the root cause yet.

**Comment by bboychris168** [comment]
My issue was caused by another plugin crashing upon joining....
