### ISSUE TITLE
skins bug on new update

### ISSUE THREAD

**Issue by PUTSUKE** [kgns/weapons#200]
some skins are bug on the new update, like AK-47 | X-Ray, AWP | Fade and some others, probably you already know that but I'm hope you fix it ASAP. congrats for the work you are doing with this and gloves plugins :)

**Comment by Shaneajm** [comment]
Also experiencing this issue, they look like the AWP Whiteout or are just gray. Configs pulled directly with the tool.

**Comment by Shaneajm** [comment]
You can fix this by changing the index in the `config.sp` file from 4 to 5 and it should fix it. Make sure to recompile the plugin,

```int counter = 0;
		char weaponTemp[20];
		do {
			char name[64];
			char index[5];
			char classes[1024];
```

**Comment by kgns** [comment]
https://github.com/kgns/weapons/releases/tag/v1.7.1
