### ISSUE TITLE
Неправильная выдача индексов окраски

### ISSUE THREAD

**Issue by yododo** [kgns/weapons#202]
Например, скин:
```
"index"		"1001"
"classes"	"weapon_m4a1_silencer;"
```
получает окраску:
```
"index"		"100"
"classes"	"weapon_aug;weapon_p90;weapon_mag7;weapon_mp9;weapon_scar20;"
```

**Comment by Melzys** [comment]
Откуда Вы взяли индексы такие?

**Comment by ZUBAT** [comment]
> Откуда Вы взяли индексы такие?

Новая операция. В чтении конфига есть ограничение на 4 символа.. можно попробовать апнуть до 5. и скомпилить.

**Comment by yododo** [comment]
> > Откуда Вы взяли индексы такие?
> 
> Новая операция. В чтении конфига есть ограничение на 4 символа.. можно попробовать апнуть до 5. и скомпилить.

Я что-то перед работой покопался, не нашёл где. Если до вечера никто не пофиксит, буду искать дальше.

**Comment by HenryTownshand** [comment]
> > > Откуда Вы взяли индексы такие?
> > 
> > 
> > Новая операция. В чтении конфига есть ограничение на 4 символа.. можно попробовать апнуть до 5. и скомпилить.
> 
> Я что-то перед работой покопался, не нашёл где. Если до вечера никто не пофиксит, буду искать дальше.

75 строчка в config.sp

**Comment by kgns** [comment]
fixed by #204
