### ISSUE TITLE
compile error "DefIndexByClass"

### ISSUE THREAD

**Issue by freakexeuLow** [kgns/weapons#205]
Hey Kgns :3

an error appears when compiling with the new version: symbol is never used: "DefIndexByClass"
```
Sourcemod version: 1.10 - build 6499
PTaH version: 1.13 (the new)
```
Thanks for the update and have a nice weekend 👍🏼

**Comment by kgns** [comment]
that's not an error, it should be a warning and should not affect the compilation process

**Comment by freakexeuLow** [comment]
> that's not an error, it should be a warning and should not affect the compilation process

okay, had seen the same error in the Sourcemod Forum but you didn't answer it.....if you want, you can close the topic if it is only a warning 👍🏼
