### ISSUE TITLE
New skin display Storm or Tornado

### ISSUE THREAD

**Issue by samyycX** [kgns/weapons#207]
I use the CSGOItemParserForWeaponsPlugin update the weapon config, it works, but some new skin (like ak47-xray) display Storm or Tornato. I try to use the config on the github, but it report an error.

`KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\configs\weapons\weapons_schinese.cfg`

`KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\configs\weapons\weapons_schinese.cfg`

`KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\configs\weapons\weapons_schinese.cfg`

`KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\configs\weapons\weapons_schinese.cfg`

`KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\configs\weapons\weapons_schinese.cfg`

`KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\configs\weapons\weapons_schinese.cfg`
`(*鍦颁笅姘?),`
`L 12/04/2020 - 20:31:10: [SM] Exception reported: CFG File not found: ``addons\sourcemod\configs\weapons\weapons_schinese.cfg`
`L 12/04/2020 - 20:31:10: [SM] Blaming: weapons.smx`
`L 12/04/2020 - 20:31:10: [SM] Call stack trace:`
`L 12/04/2020 - 20:31:10: [SM]   [0] SetFailState`
`L 12/04/2020 - 20:31:10: [SM]   [1] Line 54, tmp/addons/sourcemod/scripting/weapons/config.sp::ReadConfig`
`L 12/04/2020 - 20:31:10: [SM]   [2] Line 64, tmp/addons/sourcemod/scripting/weapons/forwards.sp::OnConfigsExecuted`

And sorry for my bad english

**Comment by crashzk** [comment]
https://github.com/kgns/weapons/releases/tag/v1.7.1

**Comment by samyycX** [comment]
> https://github.com/kgns/weapons/releases/tag/v1.7.1

thanks! it works
