### ISSUE TITLE
 Got theese errors :/ How can i fix it? :)

### ISSUE THREAD

**Issue by seeuinhell95** [kgns/weapons#212]
[SM] Exception reported: Array index out-of-bounds (index 49, limit 49)
[SM] Blaming: weapons_knife.smx
[SM] Call stack trace:
[SM]   [1] Line 20, weapons/hooks.sp::GiveNamedItemPre
[SM]   [3] GivePlayerItem
[SM]   [4] Line 864, zr/weapons/weapons.inc::WeaponsRefreshClientWeapon
[SM]   [5] Line 939, zr/weapons/weapons.inc::WeaponsRefreshAllClientWeapons
[SM]   [6] Line 370, zr/weapons/weapons.inc::WeaponsOnClientSpawnPost
[SM]   [7] Line 218, zr/event.inc::EventPlayerSpawnPost

[weapons.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:1:528642111')" error: "UNIQUE constraint failed: weapons.steamid"

[weapons.smx] Insert Query failed! query: "INSERT INTO weapons (steamid) VALUES ('STEAM_1:0:479357143')" error: "UNIQUE constraint failed: weapons.steamid"

**Comment by kgns** [comment]
those errors are unimportant, do not break anything and occurs on some rare cases. best to ignore
