### ISSUE TITLE
Does the use of the plugin results in a ban?

### ISSUE THREAD

**Issue by str0nixofficial** [kgns/weapons#214]
My question is: Does the use of the plugin results in a ban?
Thanks for your answer!

**Comment by daanvangeloven** [comment]
**Valve hasn't given out bans in a long time but this is still their official statement:**

> CS:GO community servers provide valuable experiences to players and communities, and are serving more players than ever before. Over the past month, 3.1 mln unique players were observed playing on community servers and this number keeps growing each month.
> 
> We're aware that some server operators are offering to their players false inventories and/or profiles as a free or paid service via mods on their servers. These mods inaccurately report the contents of a players' inventory and/or matchmaking status, devaluing both and potentially creating a confusing experience for players.
> 
> Therefore, we are asking server operators to remove any mods and plugins that falsify the contents of a players' profile or inventory.
> 
> To be clear, the services that should not be offered on a community server include (but are not limited to):
> 
> Allowing players to claim temporary ownership of CS:GO items that are not in their inventory (Weapon skins, knives, etc.).
> 
> Providing a falsified competitive skill group and/or profile rank status or scoreboard coin (e.g., Operation Challenge Coins).
> 
> Interfering with systems that allow players to correctly access their own CS:GO inventories, items, or profile.
> 
> If your server provides any of the above services then we request that you disable them. If for some reason you are unable or unsure of whether a particular plugin should be removed, feel free to contact us.
> 
> We will continue to monitor the players experience on community servers, and may reevaluate if further actions need to be taken to ensure that server operators comply with the request above.
> 
> Thanks,
> 
> The CS:GO Team

**If Valve decides to ban you and your servers than this will happen:**

> What happens if I receive a GSLT ban?
> 
> Server operators receiving a GSLT ban will receive the following in-game message:
> A server using your game server login token has been banned. Your account is now permanently banned from operating game servers, and you have a cooldown from connecting to game servers.
> 
> Players receiving this message are permanently banned from operating community servers in CS:GO and will receive a matchmaking cooldown. The matchmaking cooldown for GSLT bans restricts users from playing CS:GO matches and trading in-game items for the duration of the cooldown. For more information about cooldowns, please see our competitive cooldowns and bans FAQ.
> 
> Players wanting to host servers in the future will need to use a Steam account that has never shared a phone number with a GSLT banned account and re-purchase CS:GO.

**Comment by henriquemod** [comment]
> **Valve hasn't given out bans in a long time but this is still their official statement:**
> 
> > CS:GO community servers provide valuable experiences to players and communities, and are serving more players than ever before. Over the past month, 3.1 mln unique players were observed playing on community servers and this number keeps growing each month.
> > We're aware that some server operators are offering to their players false inventories and/or profiles as a free or paid service via mods on their servers. These mods inaccurately report the contents of a players' inventory and/or matchmaking status, devaluing both and potentially creating a confusing experience for players.
> > Therefore, we are asking server operators to remove any mods and plugins that falsify the contents of a players' profile or inventory.
> > To be clear, the services that should not be offered on a community server include (but are not limited to):
> > Allowing players to claim temporary ownership of CS:GO items that are not in their inventory (Weapon skins, knives, etc.).
> > Providing a falsified competitive skill group and/or profile rank status or scoreboard coin (e.g., Operation Challenge Coins).
> > Interfering with systems that allow players to correctly access their own CS:GO inventories, items, or profile.
> > If your server provides any of the above services then we request that you disable them. If for some reason you are unable or unsure of whether a particular plugin should be removed, feel free to contact us.
> > We will continue to monitor the players experience on community servers, and may reevaluate if further actions need to be taken to ensure that server operators comply with the request above.
> > Thanks,
> > The CS:GO Team
> 
> **If Valve decides to ban you and your servers than this will happen:**
> 
> > What happens if I receive a GSLT ban?
> > Server operators receiving a GSLT ban will receive the following in-game message:
> > A server using your game server login token has been banned. Your account is now permanently banned from operating game servers, and you have a cooldown from connecting to game servers.
> > Players receiving this message are permanently banned from operating community servers in CS:GO and will receive a matchmaking cooldown. The matchmaking cooldown for GSLT bans restricts users from playing CS:GO matches and trading in-game items for the duration of the cooldown. For more information about cooldowns, please see our competitive cooldowns and bans FAQ.
> > Players wanting to host servers in the future will need to use a Steam account that has never shared a phone number with a GSLT banned account and re-purchase CS:GO.

By 'falsified competitive skill' it includes Esea, faceit and such others csgo platforms? Valve valve....
