### ISSUE TITLE
Already configure database.cfg with mysql .type !ws in game still nothing happen

### ISSUE THREAD

**Issue by ElectronicBD** [kgns/weapons#224]
i use xftp7 to copy corresponding files such as sm mm path weapon to ubuntu 
Ubuntu 20.04 LTS    mysql  ufw firewall  is disable
here is my databases.cfg
"Databases"
{
	"driver_default"		"mysql"
	
	// When specifying "host", you may use an IP address, a hostname, or a socket file path
	
	"SKINS"
	{
		"driver"			"mysql"
		"host"				"*.***.**.***"
		"database"			"SKINS"
		"user"				"****"
		"pass"				"*********"
		"port"			"3306"
	}
	
	"storage-local"
	{
		"driver"			"sqlite"
		"database"			"sourcemod-local"
	}

	"clientprefs"
	{
		"driver"			"sqlite"
		"host"				"localhost"
		"database"			"clientprefs-sqlite"
		"user"				"root"
		"pass"				""
		//"timeout"			"0"
		//"port"			"0"
	}
                "default"
	{
		"driver"			"default"
		"host"				"localhost"
		"database"			"sourcemod"
		"user"				"root"
		"pass"				""
		//"timeout"			"0"
		//"port"			"0"
	}
}

**Comment by ElectronicBD** [comment]
yeah but i have already did these steps and type !ws still not funciton. I have try sqlite connect instead which still not working.By the way ,PtaH is installed. Perhap this error log connect to this issue :


/home/ubuntu/.steam/sdk32/steamclient.so
with error:
/home/ubuntu/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
 failed to dlopen /home/ubuntu/Steam/steamapps/common/Counter-Strike Global Offensive Beta - Dedicat
ed Server/csgo/addons/metamod/bin/linux64/server.so error=/home/ubuntu/Steam/steamapps/common/Counte
r-Strike Global Offensive Beta - Dedicated Server/csgo/addons/metamod/bin/linux64/server.so: wrong E
LF class: ELFCLASS64
Unable to load plugin "addons/metamod/bin/linux64/server"

**Comment by officialtezz** [comment]
Can you send the full console log?

**Comment by ElectronicBD** [comment]
Problem solved.Due to the broken file which named weapon.smx.Maybe there is some problems with my unzip software.
