### ISSUE TITLE
Skins Missing From Menu + Black Skins

### ISSUE THREAD

**Issue by Shaneajm** [kgns/weapons#229]
I updated my weapons config files and noticed that some skins are missing completely from the menu. Specially the AWP | Desert Hydra. Certain skins also show up as black - Butterfly Knife | Autotronic.

I assumed it could've been an index issue as that was the last problem but it didn't fix the issue. I'm sure you're aware of this issue but I wanted to post so when you start working on the update you know what to expect.

**Comment by Shaneajm** [comment]
Skins are not missing from the menu, just not in the order I expected. The black knives are still an issue though.

**Comment by nuxencs** [comment]
The black knifes are a game issue not a plugin issue.

**Comment by wheeIer** [comment]
New collections came out.

**Comment by nuxencs** [comment]
> New collections came out.

Yes and they are bugged for everybody else as well not just this plugin
