### ISSUE TITLE
Issue with menu popping up

### ISSUE THREAD

**Issue by kapaa2k** [kgns/weapons#232]
Hello

I added the newest PTaH and version of the plugin to my server and even when I typed "sm plugins load weapons" it said that the plugin has loaded but when I try to type !knife or !ws, it doesn't work. I also added a gloves plugin and that is working perfectly. The console says "Tried to look up command say as if it were a variable." after I put into the command.

If there's anything else needed then let me know.

**Comment by kgns** [comment]
This means that the plugin did not load successfully and that should generate error log, can you send it?

**Comment by kapaa2k** [comment]
[errors_20211031.log](https://github.com/kgns/weapons/files/7449669/errors_20211031.log)

**Comment by kgns** [comment]
as you can see from the logs, you could not properly install PTaH so the plugin does not work.
