### ISSUE TITLE
Version v1.7.6 removed the Random Knife option

### ISSUE THREAD

**Issue by crashzk** [kgns/weapons#249]
**Version v1.7.6** removed the **Random Knife** option, I believe it must be because it was spawned from the branch `master` , and the random knife option is in the branch `dev`.

I believe these two branches need to be merged and then generate a new version, correct?

**Comment by kgns** [comment]
yes but I don't think those features on dev branch are not ready to be released yet, that's why they're not merged

**Comment by crashzk** [comment]
I understand, in case I could update the list of skins on it too, I use this version in case. Or just get the skins files from the branch master  and send it to the server, just the list of skins in case.

**Comment by kgns** [comment]
I merged master into dev so dev also has the latest additions + unreleased features, I think this is what you wanted (you'll have to compile the plugin yourself ofc)
