### ISSUE TITLE
Revolution Case update

### ISSUE THREAD

**Issue by kingdragox99** [kgns/weapons#267]
Can you update plugins for Revolution Case Skins ?

**Comment by stefanx111** [comment]
You are probbably in `dev` branches which I don't know why it is default. 
Switch to [master](https://github.com/kgns/weapons/tree/master) branches to get last config.

**Comment by larinhagoddess** [comment]
@stefanx111 I can't find the download, last time I found the "Weapons v1.7.7" but this time I can't find the update.

**Comment by stefanx111** [comment]
@larinhagoddess yes, press code then download zip and upload only config folder

**Comment by larinhagoddess** [comment]
I'm probably doing something wrong... it keeps saying that it's unsupported filetype: https://prnt.sc/5iWpGufIieZO :( :( :( what am I doing wrong?

**Comment by kgns** [comment]
https://build.kgns.dev/job/csgo-weapons/lastSuccessfulBuild/artifact/build/weapons-65.zip
