### ISSUE TITLE
Anubis Collection update

### ISSUE THREAD

**Issue by sushches7vo** [kgns/weapons#272]
A new Anubis collection has been released. Where can I get the current update for the plugin? Maybe there is a discord server where updates are released.

**Comment by BogdanWDK** [comment]
Add the following in **addons/sourcemod/configs/weapons/weapons_english.cfg**
`//Anubis
    	"Eye of Horus *"
    	{
        	"index"        "1255"
        	"classes"    "weapon_m4a1;"
    	}        
    	"Waters of Nephthys *"
    	{
        	"index"        "1241"
        	"classes"    "weapon_famas;"
    	}    
    	"Apep's Curse *"
    	{
        	"index"        "1248"
        	"classes"    "weapon_p250;"
    	}
    	"Ramese's Reach *"
    	{
        	"index"        "1240"
        	"classes"    "weapon_glock;"
    	}
    	"Sobek's Bite *"
    	{
        	"index"        "1247"
        	"classes"    "weapon_nova;"
    	}        
    	"ScaraB Rush *"
    	{
        	"index"        "1250"
        	"classes"    "weapon_p90;"
    	}        
    	"Black Nile *"
    	{
        	"index"        "1239"
        	"classes"    "weapon_awp;"
    	}
    	"Steel Delta *"
    	{
        	"index"        "1238"
        	"classes"    "weapon_ak47;"
    	}        
    	"Copper Coated *"
    	{
        	"index"        "1245"
        	"classes"    "weapon_mag7;"
    	}    
    	"Mummy's Rot *"
    	{
        	"index"        "1252"
        	"classes"    "weapon_tec9;"
    	}        
    	"Desert Tacticalx *"
   	{
        	"index"        "1253"
        	"classes"    "weapon_usp_silencer;"
    	}    
    	"Mud-Spec  *"
    	{
        	"index"        "1243"
        	"classes"    "weapon_m4a1_silencer;"
    	}        
    	"Azure Glyph *"
    	{
        	"index"        "1251"
        	"classes"    "weapon_ssg08;"
    	}    
    	"Echoing Sands *"
    	{
        	"index"        "1244"
        	"classes"    "weapon_mac10;"
    	}        
    	"Sunbaked *"
    	{
        	"index"        "1246"
        	"classes"    "weapon_mp7;"
    	}
    	"Inlay *"
    	{
        	"index"        "1237"
        	"classes"    "weapon_revolver;"
    	}    
    	"Hieroglyph *"
    	{
        	"index"        "1253"
        	"classes"    "weapon_xm1014;"
    	}
    	"Snake Pit *"
    	{
        	"index"        "1249"
        	"classes"    "weapon_aug;"
    	}        
    	"Submerged *"
    	{
        	"index"        "1242"
        	"classes"    "weapon_m249;"
    	} `


https://forums.alliedmods.net/showpost.php?p=2803324&postcount=1847

**Comment by kgns** [comment]
master branch have been updated
