### ISSUE TITLE
After update (1.36.6.3/13663 825/7331) plugin cash server

### ISSUE THREAD

**Issue by Nerus87** [kgns/weapons#63]
*** ERROR *** Excessive sizelevel (1515) for element
*** ERROR *** Excessive sizelevel (1516) for element
*** ERROR *** Excessive sizelevel (1517) for element
*** ERROR *** Excessive sizelevel (1518) for element
*** ERROR *** Excessive sizelevel (1519) for element
*** ERROR *** Excessive sizelevel (1520) for element
*** ERROR *** Excessive sizelevel (1521) for element
*** ERROR *** Excessive sizelevel (1522) for element
*** ERROR *** Excessive sizelevel (1523) for element
*** ERROR *** Excessive sizelevel (1524) for element
*** ERROR *** Excessive sizelevel (1525) for element
*** ERROR *** Excessive sizelevel (1526) for element
*** ERROR *** Excessive sizelevel (1527) for element
*** ERROR *** Excessive sizelevel (1528) for element
*** ERROR *** Excessive sizelevel (1529) for element
*** ERROR *** Excessive sizelevel (1530) for element
*** ERROR *** Excessive sizelevel (1531) for element
*** ERROR *** Excessive sizelevel (1532) for element

**Comment by Nerus87** [comment]
I've update PTaH to newest version and drop database, but after some player join iv'e got crash without reason, I guess its' affected by new skins, please handle prevent from crash when new items cumming.

**Comment by ZeitZumKiffen** [comment]
yep, same problem after update the new ws files^^ so now i use the old one, and the server is still running fine

**Comment by Nerus87** [comment]
So how to use plugin without PTaH - used only for compiling?

**Comment by kaganus** [comment]
> I myself am not using PTaH **or the plugin atm**

**Comment by ZeitZumKiffen** [comment]
Okay and thanks for the info kaganus

**Comment by Nerus87** [comment]
Problem was solved with SM update.

**Comment by nguyenbaodanh** [comment]
> Problem was solved with SM update.

using latest sm and weapons plugin, server still freeze

**Comment by kaganus** [comment]
not every server freeze/crash is related to this plugin
- if you use SM 1.9 > 6265
- if you use Weapon&Knives 1.3.2
- if you DO NOT use any other plugin that uses PTaH hooks
your server will not crash because of PTaH or this plugin. your best bet would be to look at other plugins/extensions and/or provide crash log/accelerator log

**Comment by nguyenbaodanh** [comment]
there is one other plugin use ptah , let me delete and try

**Comment by nguyenbaodanh** [comment]
sm exts list
12:21:08 [SM] Displaying 18 extensions:
         [01] cURL Extension (1.3.0.0): cURL Extension
         [02] Setinfo Crash Fix (1.0): Prevents setinfo cvar spam
         [03] SDK Tools (1.9.0.6267): Source SDK Tools
         [04] BinTools (1.9.0.6267): Low-level C/C++ Calling API
         [05] CS Tools (1.9.0.6267): CS extended functionality
         [06] Top Menus (1.9.0.6267): Creates sorted nested menus
         [07] Socket (3.0.1): Socket extension for SourceMod
         [08] Client Preferences (1.9.0.6267): Saves client preference settings
         [09] SQLite (1.9.0.6267): SQLite Driver
         [10] Regex (1.9.0.6267): Provides regex natives for plugins
         [11] SDK Hooks (1.9.0.6267): Source SDK Hooks
         [12] REST in Pawn (1.0.5): Provides HTTP and JSON natives for plugins
         [13] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
         [14] SMJansson (2.3.1/3): JSON parser/writer
         [15] GeoIP (1.9.0.6267): Geographical IP information
         [16] PTaH (P Tools and Hooks) (1.0.9): Expanding sdkhooks and sdktools
         [17] <OPTIONAL> file "steamtools.ext.dll": The specified module could not be found.
         
         [18] MySQL-DBI (1.9.0.6267): MySQL driver implementation for DBI

sm plugins list:
[SM] Listing 56 plugins:
           01 "Admin File Reader" (1.9.0.6267) by AlliedModders LLC
           02 "Admin Help" (1.9.0.6267) by AlliedModders LLC
           03 "Admin Menu" (1.9.0.6267) by AlliedModders LLC
           04 "Anti-Flood" (1.9.0.6267) by AlliedModders LLC
           05 "Plugin Autoupdater" (1.5) by MikeJS
           06 "Basic Chat" (1.9.0.6267) by AlliedModders LLC
           07 "Basic Comm Control" (1.9.0.6267) by AlliedModders LLC
           08 "Basic Commands" (1.9.0.6267) by AlliedModders LLC
           09 "Basic Info Triggers" (1.9.0.6267) by AlliedModders LLC
           10 "Basic Votes" (1.9.0.6267) by AlliedModders LLC
           11 "Client Preferences" (1.9.0.6267) by AlliedModders LLC
           12 "[Any] Command Cooldowns" (14.1117) by Derek D. Howard
           13 "CSGO Anti Team Flash" (1.3) by Franc1sco franug, Twisted|Panda (Orig: SAMURAI16/Kigen)
           14 "[CS:GO] Auto Pick" (1.0.0) by Panduh (AlliedMods: thetwistedpanda)
           15 "[CS:GO] SpawnTools7" (1.0.1) by meng & IDDQD
           16 "[Discord] Admin Session Log" (1.0) by CrazyHackGUT aka Kruzya
           17 "[Discord] Core" (1.0.8) by CrazyHackGUT aka Kruzya
           18 "Discord API" (0.1.12) by Deathknife
           19 "[Discord] Admin Log" (0.3.1) by Lord FEAR
           20 "[Discord] Simple Report System" (1.2.2) by CrazyHackGUT aka Kruzya
           21 "[Discord] SourceBans + SourceComms" (1.2.2) by CrazyHackGUT aka Kruzya
           22 "DR.API AFK MANAGER" (1.0.1) by Dr. Api
           23 "Fun Commands" (1.9.0.6267) by AlliedModders LLC
           24 "Fun Votes" (1.9.0.6267) by AlliedModders LLC
           25 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
           26 "RankMe" (3.0.3.Kento.29.2) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
           27 "MapChooser" (1.8.0.5995) by AlliedModders LLC
           28 "Nextmap" (1.9.0.6267) by AlliedModders LLC
           29 "Map Nominations" (1.5.4-dev+4028) by AlliedModders LLC
           30 "Player Commands" (1.9.0.6267) by AlliedModders LLC
           31 "RandomCycle" (1.7.3-dev+5298) by AlliedModders LLC
           32 "Reserved Slots" (1.9.0.6267) by AlliedModders LLC
           33 "Rock The Vote" (1.5.4-dev+4028) by AlliedModders LLC
           34 "seDirector" (2.4) by Asher Software
           35 "ServerAdvertisements3" (3.1.3) by ESK0
           36 "Server Info" (1.1.0) by EmreBulut
           37 "???????????? sm plugins" (1.1) by Pheonix (??????????????)
           38 "Sound Commands" (1.9.0.6267) by AlliedModders LLC
           39 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
           40 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
           41 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
           42 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
           43 "SQL Admin Manager" (1.5.3-dev+4005) by AlliedModders LLC
           44 "ATAC - Blind Punishment" (2.5.3) by GameConnect
           45 "ATAC - Slay Punishment" (2.5.3) by GameConnect
           46 "Advanced Team Attack Control" (2.5.3) by GameConnect
           47 "Reflect team damage" (1.3) by mad_hamster, modified by Snake 60 & Geel9
           48 "[Cs:s & Cs:go]Teammate attack show all" (1.1) by Bacardi & VieuxGnome
           49 "Updater" (1.2.2) by GoD-Tony
           50 "VIP Stuff" (1.0) by Mr.Derp
           51 "Weapon Restrict" (3.1.7) by Dr!fter
           52 "Chat-Processor" (2.0.8) by Keith Warren (Drixevel)
           53 "Chat Colors CSGO" (1.4) by Pheonix (??, 
           54 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
           55 "Unique Chat" (1.0.1) by MitchDizzle
           56 "Give Weapon" (1.0) by Kiske

deleted 1 other plugin that use ptah, let see if it still freeze without any error log

**Comment by kaganus** [comment]
37 "???????????? sm plugins" (1.1) by Pheonix (??????????????)
this probably is using PTaH too
type;
sm exts unload 16
this wont unload PTaH but will give you a list of plugins that depend on PTaH, you should only have weapons.smx on that list

**Comment by kaganus** [comment]
oh, I cannot vouch for Windows version of PTaH, you should ask for help from PTaH author then
