### ISSUE TITLE
MY SERVER CRASHNG ON PLAYER CONNECT BCOZ OF WEAPON.SMX

### ISSUE THREAD

**Issue by Bearbobs** [kgns/weapons#72]
enabling weapons.smx is crashing my server..
 it works fine without it

**Comment by Bearbobs** [comment]
DONE

**Comment by BlackYuzia** [comment]
Srly?

**Comment by kgns** [comment]
can you please tell us what you did wrong on first try, and what fixed it? may help other people in the future.
