### ISSUE TITLE
Permissions Query

### ISSUE THREAD

**Issue by Jonnyfencing1** [kgns/weapons#73]
How can I add permissions for all my players to use these commands in my server?
Sorry if this is known already I couldn't see it

**Comment by kgns** [comment]
there are no permissions to be configured. by default everyone can use every command, and there are no options to restrict this, and it will not be added in the future (in the default repo at least)

**Comment by Jonnyfencing1** [comment]
Then this is weird because I can use the command but my friends can't

**Comment by kgns** [comment]
well thats your issue, not this plugins. search for sourcemod admin overrides on google, this is not the place for it
