### ISSUE TITLE
[Feature Request Paid] - Privilege Option - Admin Flags 

### ISSUE THREAD

**Issue by paulocrash** [kgns/weapons#75]
I would like to know if it would be possible in the next updates to put the flags option in the plugin.

He would be willing to pay for such a version, and he would be very happy to get rid of them all.

It would be possible, if yes, what value is right for this change, I thought of something around 5 to 10 euros, would that be fair to you?

@kgns

**Comment by SniperHero007** [comment]
> I would like to know if it would be possible in the next updates to put the flags option in the plugin.
> 
> He would be willing to pay for such a version, and he would be very happy to get rid of them all.
> 
> It would be possible, if yes, what value is right for this change, I thought of something around 5 to 10 euros, would that be fair to you?
> 
> @kgns

I can help you

**Comment by kgns** [comment]
As stated before, flag options will not be added/supported on this repo

**Comment by paulocrash** [comment]
I see, would it be possible to do another repo? A private version.

**Comment by morpig** [comment]
He created this plugin for everyone to be able to use the WS feature.

This plugin is open source and you can fork it for your own use.

**Comment by paulocrash** [comment]
I understand, is that as this in his own official topic of the plugin, if you want any change with this purpose would have to pay. So yes, I prefer to pay for it as an author if you want it in the future, it covers itself for that version or makes it available with it, now I guarantee if you ask any other programmer that I pay to do this I'm sure he'll sell these modifications. Anyway, thank you anyway, I'll be seeing how I can do then, thanks again.
