### ISSUE TITLE
bug knife

### ISSUE THREAD

**Issue by Jalorussian** [kgns/weapons#76]
knife dupe on surf and awp maps on hlmod i see fix but for 1.3.1

**Comment by kgns** [comment]
i have never experienced this problem, can you send a link to the 1.3.1 fix so i can check if it's a real problem and the fix is a real fix?

**Comment by Jalorussian** [comment]
![image](https://user-images.githubusercontent.com/30295147/54286761-82f4f700-45b5-11e9-8745-befa15a15633.png)

[Desktop.zip](https://github.com/kgns/weapons/files/2961888/Desktop.zip)

**Comment by SamyR0** [comment]
yea i also get this on awp maps , like , awp_lego_csgo or awp_india_csgo , the map is made so can drop the default knife and any other gun without awp so it's map related stuff

**Comment by kgns** [comment]
the problem here is from other plugins (such as timers for surf etc.) giving players knives when they type !knife without checking if the player already had a knife or not. fix for this is needed to be implemented on those plugins, not this one.
