### ISSUE TITLE
[bug] Drop and Pick Knife!!

### ISSUE THREAD

**Issue by Drmohammad11** [kgns/weapons#79]
hi!
i used "mp_drop_knife_enable 1" but i can not pick any knifes on the ground!!
please fix this bug

**Comment by kgns** [comment]
that's not a bug, that's by choice. enabling picking "fake" knives from the ground sometimes crashes servers. that is why it is only enabled for Deathmatch servers, as the plugin can only function with it enabled in dm gamemode.
