### ISSUE TITLE
Error function prototypes 

### ISSUE THREAD

**Issue by RED4911** [kgns/weapons#81]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// weapons.sp
//
// C:\Users\Desktop\sourcemod\scripting\weapons.sp(69) : error 100
: function prototypes do not match
// C:\Users\Desktop\sourcemod\scripting\weapons.sp(70) : error 100
: function prototypes do not match
//
// 2 Errors.
//
// Compilation Time: 1 sec
// ----------------------------------------

Press enter to exit ...

**Comment by kgns** [comment]
use new include file from PTaH 1.10
