### ISSUE TITLE
New version didn't work ?

### ISSUE THREAD

**Issue by nguyenbaodanh** [kgns/weapons#85]
Plugins listed like no errors but in game can't choose skins, nothing appeared 

L 03/16/2019 - 00:04:28: SourceMod error session started
L 03/16/2019 - 00:04:28: Info (map "de_cache") (file "errors_20190316.log")
L 03/16/2019 - 00:04:28: [SM] Exception reported: Menu handle 0 is invalid (error 4)
L 03/16/2019 - 00:04:28: [SM] Blaming: kaganus weapons\weapons.smx
L 03/16/2019 - 00:04:28: [SM] Call stack trace:
L 03/16/2019 - 00:04:28: [SM]   [0] Menu.Display
L 03/16/2019 - 00:04:28: [SM]   [1] Line 115, weapons/menus.sp::WeaponMenuHandler
L 03/16/2019 - 00:13:46: [SM] Exception reported: Menu handle 0 is invalid (error 4)
L 03/16/2019 - 00:13:46: [SM] Blaming: kaganus weapons\weapons.smx
L 03/16/2019 - 00:13:46: [SM] Call stack trace:
L 03/16/2019 - 00:13:46: [SM]   [0] Menu.Display
L 03/16/2019 - 00:13:46: [SM]   [1] Line 115, weapons/menus.sp::WeaponMenuHandler
L 03/16/2019 - 00:20:49: Error log file session closed.

**Comment by kgns** [comment]
cannot replicate, probably wrong setup
