### ISSUE TITLE
Not compile SM 1.9 - build 6280

### ISSUE THREAD

**Issue by megoRU** [kgns/weapons#86]
![image](https://user-images.githubusercontent.com/23276305/57077715-68a5e280-6cf5-11e9-8ca6-75063fe33507.png)

**Comment by kgns** [comment]
update your sourcemod includes files and try again please

**Comment by megoRU** [comment]
@kgns yep i compiled on clear sm folder)

**Comment by megoRU** [comment]
and 0 error
