### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hmglife** [kgns/weapons#89]
It didn't work after Update CS: GO from 05-08-2019 (version 1.36.9.4). Only !gloves could work.
also please give a function that t and ct can choose different knifes or skins , and users can change skin's pattern index not only float. Thanks!

**Comment by hmglife** [comment]
I think it didn't work only in insecure mode not in servers.

**Comment by bboychris168** [comment]
i installed everything, but nothing seems to work?

**Comment by kgns** [comment]
make sure to follow the installation steps provided for you, there are no problems with the plugin
