### ISSUE TITLE
Unable to load plugin "weapons.smx": Error detected in plugin startup 

### ISSUE THREAD

**Issue by SanjaySRocks** [kgns/weapons#98]
How to fix this error?

L 07/23/2019 - 17:49:32: SourceMod error session started
L 07/23/2019 - 17:49:32: Info (map "de_mirage") (file "errors_20190723.log")
L 07/23/2019 - 17:49:32: [SM] Exception reported: Invalid event PTaH_HookType specified
L 07/23/2019 - 17:49:32: [SM] Blaming: weapons.smx
L 07/23/2019 - 17:49:32: [SM] Call stack trace:
L 07/23/2019 - 17:49:32: [SM]   [0] PTaH
L 07/23/2019 - 17:49:32: [SM]   [1] Line 69, tmp/addons/sourcemod/scripting/weapons.sp::OnPluginStart
L 07/23/2019 - 17:49:32: [SM] Unable to load plugin "weapons.smx": Error detected in plugin startup (see error logs)
L 07/23/2019 - 17:51:39: SourceMod error session started
L 07/23/2019 - 17:51:39: Info (map "de_mirage") (file "errors_20190723.log")
L 07/23/2019 - 17:51:39: [SM] Exception reported: Invalid event PTaH_HookType specified
L 07/23/2019 - 17:51:39: [SM] Blaming: weapons.smx
L 07/23/2019 - 17:51:39: [SM] Call stack trace:
L 07/23/2019 - 17:51:39: [SM]   [0] PTaH
L 07/23/2019 - 17:51:39: [SM]   [1] Line 69, tmp/addons/sourcemod/scripting/weapons.sp::OnPluginStart
L 07/23/2019 - 17:51:39: [SM] Unable to load plugin "weapons.smx": Error detected in plugin startup (see error logs)

**Comment by Cyritz** [comment]
I'm getting the same error using the latest PTaH release from https://ptah.zizt.ru/ and both most recent dev versions of Metamod and Sourcemod.

**Comment by kgns** [comment]
if you want to use the latest PTaH from https://ptah.zizt.ru/ before I release a new version, use the latest from https://ci.kgns.me/job/csgo-weapons/lastSuccessfulBuild/artifact/build/weapons-15.zip

**Comment by rabi07** [comment]
hey need help.. i have same issue ..dont know what to do
